// CTN Vocab — Part 1: People, Body & Health, Home, Food & Drink
// Topics follow the English Vocabulary Organiser syllabus; definitions and examples are original.
const VOCAB = { sections: [

{ name:"People", emoji:"👥", units:[
  { id:1, title:"Age", emoji:"🎂", words:[
    { w:"baby", pos:"noun", d:"a very young child", ex:"The baby is sleeping in her cot." },
    { w:"toddler", pos:"noun", d:"a small child who is learning to walk", ex:"The toddler fell down and laughed." },
    { w:"child", pos:"noun", d:"a young boy or girl", ex:"Every child in the class got a book." },
    { w:"teenager", pos:"noun", d:"a person between 13 and 19 years old", ex:"My cousin is a teenager who loves music." },
    { w:"adult", pos:"noun", d:"a fully grown person", ex:"You must be an adult to drive a car." },
    { w:"elderly", pos:"adjective", d:"a polite word for old people", ex:"We helped an elderly man carry his bags." },
    { w:"young", pos:"adjective", d:"not old", ex:"She is too young to watch this film." },
    { w:"generation", pos:"noun", d:"people born around the same time", ex:"My grandparents come from a different generation." },
    { w:"birthday", pos:"noun", d:"the day you were born, celebrated every year", ex:"We sang songs at her birthday party." },
    { w:"grow up", pos:"phrasal verb", d:"to change from a child into an adult", ex:"I want to be a doctor when I grow up." },
  ]},
  { id:2, title:"Stages of life", emoji:"🌱", words:[
    { w:"birth", pos:"noun", d:"the moment a baby comes into the world", ex:"She was present at the birth of her nephew." },
    { w:"childhood", pos:"noun", d:"the time when you are a child", ex:"He had a happy childhood in the countryside." },
    { w:"adolescence", pos:"noun", d:"the teenage years between child and adult", ex:"Adolescence can be a difficult time for everyone." },
    { w:"single", pos:"adjective", d:"not married", ex:"My uncle is still single at forty." },
    { w:"engaged", pos:"adjective", d:"having promised to marry someone", ex:"They got engaged last summer in Paris." },
    { w:"married", pos:"adjective", d:"having a husband or wife", ex:"My parents have been married for twenty years." },
    { w:"career", pos:"noun", d:"the jobs you do through your working life", ex:"She wants a career in medicine." },
    { w:"retirement", pos:"noun", d:"the time when you stop working forever", ex:"My grandfather enjoys fishing in his retirement." },
    { w:"decision", pos:"noun", d:"a choice you make after thinking", ex:"Choosing a university is a big decision." },
    { w:"lifetime", pos:"noun", d:"the whole time that someone is alive", ex:"He saw many changes in his lifetime." },
  ]},
  { id:5, title:"Family", emoji:"👨‍👩‍👧‍👦", words:[
    { w:"parents", pos:"noun", d:"your mother and father", ex:"My parents met at university in Tashkent." },
    { w:"relatives", pos:"noun", d:"all the people in your family", ex:"Our relatives visit us every holiday." },
    { w:"cousin", pos:"noun", d:"the child of your uncle or aunt", ex:"My cousin lives in the next street." },
    { w:"nephew", pos:"noun", d:"the son of your brother or sister", ex:"Her nephew is starting school this year." },
    { w:"niece", pos:"noun", d:"the daughter of your brother or sister", ex:"I bought a present for my little niece." },
    { w:"uncle", pos:"noun", d:"the brother of your mother or father", ex:"My uncle taught me to ride a bike." },
    { w:"aunt", pos:"noun", d:"the sister of your mother or father", ex:"My aunt makes the best plov in town." },
    { w:"grandparents", pos:"noun", d:"the parents of your parents", ex:"My grandparents live in a quiet village." },
    { w:"twins", pos:"noun", d:"two children born together to the same mother", ex:"The twins wear the same clothes every day." },
    { w:"adopt", pos:"verb", d:"to take a child into your family legally", ex:"They decided to adopt a little girl." },
  ]},
  { id:6, title:"Friends", emoji:"🤝", words:[
    { w:"friendship", pos:"noun", d:"the special relationship between friends", ex:"Their friendship started in primary school." },
    { w:"classmate", pos:"noun", d:"a person in your class at school", ex:"My classmate helped me with my homework." },
    { w:"neighbour", pos:"noun", d:"a person who lives next to you", ex:"Our neighbour waters our plants in summer." },
    { w:"stranger", pos:"noun", d:"a person you do not know", ex:"Never open the door to a stranger." },
    { w:"colleague", pos:"noun", d:"a person you work with", ex:"Dad plays chess with his colleague at lunch." },
    { w:"trust", pos:"verb", d:"to believe someone is honest and good", ex:"I trust my best friend with my secrets." },
    { w:"argue", pos:"verb", d:"to speak angrily because you do not agree", ex:"Good friends sometimes argue about small things." },
    { w:"apologise", pos:"verb", d:"to say sorry for something you did", ex:"He came back to apologise for being late." },
    { w:"get on", pos:"phrasal verb", d:"to have a good relationship with someone", ex:"I get on really well with my sister." },
    { w:"support", pos:"verb", d:"to help someone in a difficult time", ex:"True friends support you when things go wrong." },
  ]},
  { id:12, title:"Describing character", emoji:"💫", words:[
    { w:"kind", pos:"adjective", d:"friendly and good to other people", ex:"It was kind of you to share your lunch." },
    { w:"lazy", pos:"adjective", d:"not wanting to work or move", ex:"My cat is too lazy to catch mice." },
    { w:"hardworking", pos:"adjective", d:"putting a lot of effort into work", ex:"She is the most hardworking student in class." },
    { w:"shy", pos:"adjective", d:"nervous about talking to new people", ex:"He was too shy to ask a question." },
    { w:"confident", pos:"adjective", d:"sure about yourself and your abilities", ex:"She gave a confident answer at the interview." },
    { w:"generous", pos:"adjective", d:"happy to give money, time or help", ex:"Our generous teacher gave everyone a sweet." },
    { w:"selfish", pos:"adjective", d:"caring only about yourself", ex:"It is selfish to eat the whole cake alone." },
    { w:"honest", pos:"adjective", d:"always telling the truth", ex:"Be honest and tell me what happened." },
    { w:"polite", pos:"adjective", d:"speaking and acting with respect", ex:"Always be polite to your teachers." },
    { w:"cheerful", pos:"adjective", d:"happy and smiling most of the time", ex:"The cheerful shopkeeper greets everyone warmly." },
  ]},
  { id:14, title:"Feelings and emotions", emoji:"😊", words:[
    { w:"excited", pos:"adjective", d:"very happy about something that will happen", ex:"The kids are excited about the school trip." },
    { w:"nervous", pos:"adjective", d:"worried about something that will happen", ex:"I always feel nervous before an exam." },
    { w:"proud", pos:"adjective", d:"happy about something you or others did well", ex:"Her parents are proud of her results." },
    { w:"jealous", pos:"adjective", d:"unhappy because someone has what you want", ex:"He felt jealous of his brother's new phone." },
    { w:"embarrassed", pos:"adjective", d:"ashamed and uncomfortable in front of people", ex:"I was embarrassed when I forgot his name." },
    { w:"disappointed", pos:"adjective", d:"sad because something was not as good as you hoped", ex:"We were disappointed when the match was cancelled." },
    { w:"surprised", pos:"adjective", d:"feeling wonder at something unexpected", ex:"She was surprised by the birthday party." },
    { w:"scared", pos:"adjective", d:"afraid of something", ex:"My little sister is scared of the dark." },
    { w:"upset", pos:"adjective", d:"unhappy because something bad happened", ex:"He was upset about losing his keys." },
    { w:"calm", pos:"adjective", d:"relaxed and not worried", ex:"Stay calm and read every question slowly." },
  ]},
]},

{ name:"Body & Health", emoji:"💪", units:[
  { id:18, title:"Head and face", emoji:"🙂", words:[
    { w:"forehead", pos:"noun", d:"the part of your face above your eyes", ex:"He wiped the sweat from his forehead." },
    { w:"eyebrow", pos:"noun", d:"the line of hair above your eye", ex:"She raised one eyebrow in surprise." },
    { w:"eyelash", pos:"noun", d:"one of the small hairs on your eyelid", ex:"An eyelash fell into my eye." },
    { w:"cheek", pos:"noun", d:"the soft side part of your face", ex:"Grandma kissed me on the cheek." },
    { w:"chin", pos:"noun", d:"the bottom part of your face", ex:"The football hit him on the chin." },
    { w:"lips", pos:"noun", d:"the soft edges of your mouth", ex:"Her lips turned blue from the cold water." },
    { w:"tongue", pos:"noun", d:"the part of your mouth you taste with", ex:"The doctor asked to see my tongue." },
    { w:"beard", pos:"noun", d:"hair that grows on a man's chin", ex:"My father shaved off his long beard." },
    { w:"moustache", pos:"noun", d:"hair that grows above the lip", ex:"The policeman had a thick black moustache." },
    { w:"wrinkles", pos:"noun", d:"lines on the skin of older people", ex:"My grandmother has wrinkles around her eyes." },
  ]},
  { id:20, title:"Parts of the body", emoji:"🦵", words:[
    { w:"shoulder", pos:"noun", d:"where your arm joins your body", ex:"He carried the bag on his shoulder." },
    { w:"elbow", pos:"noun", d:"the joint in the middle of your arm", ex:"She hurt her elbow playing volleyball." },
    { w:"wrist", pos:"noun", d:"the joint between your hand and arm", ex:"He wears a watch on his left wrist." },
    { w:"knee", pos:"noun", d:"the joint in the middle of your leg", ex:"I fell and cut my knee." },
    { w:"ankle", pos:"noun", d:"the joint between your foot and leg", ex:"She twisted her ankle on the stairs." },
    { w:"chest", pos:"noun", d:"the front top part of your body", ex:"The runner felt his chest rise and fall." },
    { w:"stomach", pos:"noun", d:"the part of your body where food goes", ex:"My stomach hurts after eating too fast." },
    { w:"thumb", pos:"noun", d:"the short thick finger on your hand", ex:"The baby likes to suck her thumb." },
    { w:"heel", pos:"noun", d:"the back part of your foot", ex:"These new shoes hurt my heel." },
    { w:"muscle", pos:"noun", d:"the parts of the body that make you move", ex:"Swimming makes every muscle in your body stronger." },
  ]},
  { id:23, title:"Feeling ill", emoji:"🤒", words:[
    { w:"headache", pos:"noun", d:"a pain in your head", ex:"Loud music always gives me a headache." },
    { w:"cough", pos:"noun", d:"the noise of air pushed from your throat", ex:"His cough kept the whole family awake." },
    { w:"sneeze", pos:"verb", d:"to blow air suddenly through your nose", ex:"Dust makes me sneeze again and again." },
    { w:"fever", pos:"noun", d:"a body temperature that is too high", ex:"She stayed in bed because of a fever." },
    { w:"dizzy", pos:"adjective", d:"feeling like everything is turning around", ex:"I feel dizzy when I stand up quickly." },
    { w:"pain", pos:"noun", d:"the feeling when part of your body hurts", ex:"He felt a sharp pain in his tooth." },
    { w:"flu", pos:"noun", d:"an illness like a bad cold with fever", ex:"Half the class is at home with flu." },
    { w:"medicine", pos:"noun", d:"something you take to get better", ex:"Take this medicine three times a day." },
    { w:"rest", pos:"verb", d:"to relax and do nothing to get better", ex:"The doctor told him to rest for a week." },
    { w:"sore", pos:"adjective", d:"painful when touched or used", ex:"My throat is so sore I can hardly speak." },
  ]},
  { id:25, title:"At the doctor's", emoji:"🩺", words:[
    { w:"appointment", pos:"noun", d:"a fixed time to see someone", ex:"I have a dentist appointment at four o'clock." },
    { w:"symptom", pos:"noun", d:"a sign that shows you are ill", ex:"A runny nose is a symptom of a cold." },
    { w:"prescription", pos:"noun", d:"a paper from the doctor for medicine", ex:"Take this prescription to the pharmacy." },
    { w:"injection", pos:"noun", d:"medicine put into the body with a needle", ex:"The nurse gave him an injection in his arm." },
    { w:"bandage", pos:"noun", d:"a long piece of cloth tied around an injury", ex:"She wrapped a clean bandage around my hand." },
    { w:"examine", pos:"verb", d:"to look at something very carefully", ex:"The doctor will examine your ears and throat." },
    { w:"patient", pos:"noun", d:"a person who is treated by a doctor", ex:"The patient waited quietly in the corridor." },
    { w:"pharmacy", pos:"noun", d:"a shop that sells medicine", ex:"The pharmacy on our street is open all night." },
    { w:"recover", pos:"verb", d:"to get better after being ill", ex:"It took two weeks to recover from the flu." },
    { w:"emergency", pos:"noun", d:"a serious situation needing fast help", ex:"Call this number only in an emergency." },
  ]},
  { id:27, title:"Healthy living", emoji:"🥗", words:[
    { w:"diet", pos:"noun", d:"the food that you usually eat", ex:"A healthy diet includes fruit and vegetables." },
    { w:"exercise", pos:"noun", d:"activity that keeps your body strong", ex:"Morning exercise gives me energy all day." },
    { w:"vitamin", pos:"noun", d:"something in food that keeps you healthy", ex:"Oranges are full of vitamin C." },
    { w:"junk food", pos:"noun", d:"food that tastes good but is unhealthy", ex:"Too much junk food makes you feel tired." },
    { w:"active", pos:"adjective", d:"moving a lot and full of energy", ex:"Active children usually sleep better at night." },
    { w:"habit", pos:"noun", d:"something you do regularly without thinking", ex:"Brushing your teeth should be a daily habit." },
    { w:"stress", pos:"noun", d:"worry that makes you feel tense", ex:"Exams cause a lot of stress for students." },
    { w:"energy", pos:"noun", d:"the power your body needs to be active", ex:"Breakfast gives you energy for the whole morning." },
    { w:"weight", pos:"noun", d:"how heavy a person or thing is", ex:"The doctor checked my height and weight." },
    { w:"give up", pos:"phrasal verb", d:"to stop doing something, especially a bad habit", ex:"My father wants to give up sugary drinks." },
  ]},
]},

{ name:"Home", emoji:"🏠", units:[
  { id:28, title:"Houses and homes", emoji:"🏡", words:[
    { w:"flat", pos:"noun", d:"a home on one floor of a big building", ex:"They live in a flat on the fifth floor." },
    { w:"cottage", pos:"noun", d:"a small house in the countryside", ex:"We spent the summer in a mountain cottage." },
    { w:"floor", pos:"noun", d:"the surface you walk on inside", ex:"The cat is sleeping on the kitchen floor." },
    { w:"ceiling", pos:"noun", d:"the top surface inside a room", ex:"A beautiful lamp hangs from the ceiling." },
    { w:"roof", pos:"noun", d:"the top cover of a building", ex:"Snow covered the roof of every house." },
    { w:"stairs", pos:"noun", d:"steps that take you up or down inside", ex:"Run up the stairs and get my glasses." },
    { w:"balcony", pos:"noun", d:"a platform outside an upstairs window", ex:"We drink tea on the balcony every evening." },
    { w:"garage", pos:"noun", d:"a building where you keep a car", ex:"Dad is fixing his bike in the garage." },
    { w:"garden", pos:"noun", d:"land next to a house with plants", ex:"Roses and tulips grow in our garden." },
    { w:"neighbourhood", pos:"noun", d:"the area around your home", ex:"Our neighbourhood has a new playground." },
  ]},
  { id:29, title:"The living room", emoji:"🛋️", words:[
    { w:"sofa", pos:"noun", d:"a long soft seat for two or more people", ex:"The whole family watched TV on the sofa." },
    { w:"armchair", pos:"noun", d:"a comfortable chair with sides for your arms", ex:"Grandpa reads his newspaper in the armchair." },
    { w:"carpet", pos:"noun", d:"a thick soft cover for the floor", ex:"We bought a red carpet for the living room." },
    { w:"curtains", pos:"noun", d:"cloth that covers a window", ex:"Open the curtains and let the sun in." },
    { w:"cushion", pos:"noun", d:"a soft pillow for a chair or sofa", ex:"She hugged a cushion while watching the film." },
    { w:"bookshelf", pos:"noun", d:"a shelf for keeping books", ex:"His bookshelf is full of adventure stories." },
    { w:"fireplace", pos:"noun", d:"a place in a room where a fire burns", ex:"The children sat by the warm fireplace." },
    { w:"lamp", pos:"noun", d:"a light that stands on a table or floor", ex:"Turn on the lamp so you can read." },
    { w:"comfortable", pos:"adjective", d:"nice to sit, lie or relax on", ex:"This armchair is the most comfortable seat here." },
    { w:"cosy", pos:"adjective", d:"warm, comfortable and welcoming", ex:"The living room feels cosy in winter." },
  ]},
  { id:30, title:"The kitchen", emoji:"🍳", words:[
    { w:"fridge", pos:"noun", d:"a machine that keeps food cold", ex:"Put the milk back in the fridge." },
    { w:"oven", pos:"noun", d:"the closed box where you bake food", ex:"The bread is baking in the oven." },
    { w:"sink", pos:"noun", d:"the place where you wash dishes", ex:"The sink is full of dirty plates." },
    { w:"kettle", pos:"noun", d:"a pot for boiling water for tea", ex:"Put the kettle on and make some tea." },
    { w:"saucepan", pos:"noun", d:"a deep metal pot for cooking", ex:"Soup was boiling in the big saucepan." },
    { w:"cupboard", pos:"noun", d:"a piece of furniture with doors for storing things", ex:"The cups are in the top cupboard." },
    { w:"tap", pos:"noun", d:"the thing you turn to get water", ex:"Turn off the tap while brushing your teeth." },
    { w:"dishwasher", pos:"noun", d:"a machine that washes plates and cups", ex:"Load the dishwasher after dinner, please." },
    { w:"microwave", pos:"noun", d:"a machine that heats food very quickly", ex:"He warmed the pizza in the microwave." },
    { w:"apron", pos:"noun", d:"clothing that keeps you clean while cooking", ex:"Mum wears a blue apron when she bakes." },
  ]},
  { id:31, title:"Bedroom and bathroom", emoji:"🛏️", words:[
    { w:"pillow", pos:"noun", d:"the soft thing you put your head on in bed", ex:"I cannot sleep without my favourite pillow." },
    { w:"blanket", pos:"noun", d:"a warm cover for a bed", ex:"She pulled the blanket over her head." },
    { w:"wardrobe", pos:"noun", d:"a tall cupboard for hanging clothes", ex:"Hang your school uniform in the wardrobe." },
    { w:"mirror", pos:"noun", d:"glass that shows your reflection", ex:"He smiled at himself in the mirror." },
    { w:"towel", pos:"noun", d:"cloth you use to dry yourself", ex:"Take a clean towel for the swimming pool." },
    { w:"shower", pos:"noun", d:"where you stand to wash under falling water", ex:"A cold shower wakes me up in the morning." },
    { w:"toothbrush", pos:"noun", d:"the small brush for cleaning your teeth", ex:"Change your toothbrush every three months." },
    { w:"shampoo", pos:"noun", d:"liquid soap for washing your hair", ex:"This shampoo smells like fresh apples." },
    { w:"mattress", pos:"noun", d:"the soft part of the bed you lie on", ex:"A good mattress helps you sleep well." },
    { w:"alarm clock", pos:"noun", d:"a clock that wakes you up", ex:"My alarm clock rings at seven every morning." },
  ]},
  { id:32, title:"Jobs around the house", emoji:"🧹", words:[
    { w:"housework", pos:"noun", d:"the work of cleaning and tidying a home", ex:"Everyone in our family shares the housework." },
    { w:"ironing", pos:"noun", d:"making clothes smooth with a hot iron", ex:"Dad does the ironing on Sunday evenings." },
    { w:"laundry", pos:"noun", d:"clothes that need washing", ex:"The laundry basket is completely full again." },
    { w:"sweep", pos:"verb", d:"to clean the floor with a brush", ex:"Please sweep the kitchen after cooking." },
    { w:"mop", pos:"verb", d:"to clean the floor with water", ex:"I mop the bathroom floor every Saturday." },
    { w:"dust", pos:"verb", d:"to remove dirt from furniture", ex:"She likes to dust the shelves while singing." },
    { w:"tidy", pos:"verb", d:"to put things in their right places", ex:"Tidy your room before your friends arrive." },
    { w:"vacuum", pos:"verb", d:"to clean the carpet with a machine", ex:"He offered to vacuum the whole house." },
    { w:"polish", pos:"verb", d:"to rub something until it shines", ex:"Grandpa taught me to polish my shoes." },
    { w:"wash up", pos:"phrasal verb", d:"to clean the dishes after a meal", ex:"You cooked dinner, so I will wash up." },
  ]},
]},

{ name:"Food & Drink", emoji:"🍎", units:[
  { id:35, title:"Fruit and vegetables", emoji:"🥕", words:[
    { w:"peach", pos:"noun", d:"a soft sweet fruit with fuzzy skin", ex:"This peach is juicy and sweet." },
    { w:"pear", pos:"noun", d:"a sweet fruit that is thin at the top", ex:"He packed a pear in his lunchbox." },
    { w:"grapes", pos:"noun", d:"small round fruits that grow in bunches", ex:"Uzbek grapes are famous for their sweetness." },
    { w:"cherry", pos:"noun", d:"a small round red fruit with a stone", ex:"She put a cherry on top of the cake." },
    { w:"pineapple", pos:"noun", d:"a large sweet fruit with spiky skin", ex:"We shared a pineapple at the beach." },
    { w:"cucumber", pos:"noun", d:"a long green vegetable eaten in salads", ex:"Slice the cucumber for the fresh salad." },
    { w:"cabbage", pos:"noun", d:"a big round vegetable with many leaves", ex:"Mum cooked soup with cabbage and carrots." },
    { w:"onion", pos:"noun", d:"a round vegetable that makes you cry", ex:"Chopping an onion always makes me cry." },
    { w:"pepper", pos:"noun", d:"a red, green or yellow hollow vegetable", ex:"Add some red pepper to the plov." },
    { w:"lettuce", pos:"noun", d:"a green leafy vegetable used in salads", ex:"Wash the lettuce before you eat it." },
  ]},
  { id:36, title:"Talking about food", emoji:"😋", words:[
    { w:"delicious", pos:"adjective", d:"tasting extremely good", ex:"Your grandmother's plov is absolutely delicious." },
    { w:"tasty", pos:"adjective", d:"having a good flavour", ex:"These dumplings are cheap and tasty." },
    { w:"bitter", pos:"adjective", d:"with a strong taste like black coffee", ex:"This tea is too bitter without sugar." },
    { w:"sour", pos:"adjective", d:"with a sharp taste like lemon", ex:"The yoghurt was a little sour." },
    { w:"spicy", pos:"adjective", d:"with a hot taste like chilli", ex:"Korean carrots are spicy but delicious." },
    { w:"sweet", pos:"adjective", d:"tasting of sugar or honey", ex:"This melon is as sweet as honey." },
    { w:"fresh", pos:"adjective", d:"recently made, picked or cooked", ex:"The bakery sells fresh bread every morning." },
    { w:"stale", pos:"adjective", d:"no longer fresh, old and dry", ex:"The bread from Monday is already stale." },
    { w:"ripe", pos:"adjective", d:"ready to eat, fully grown", ex:"Wait until the tomatoes are ripe and red." },
    { w:"disgusting", pos:"adjective", d:"tasting or looking extremely bad", ex:"Cold soup with sugar sounds disgusting." },
  ]},
  { id:37, title:"Cooking", emoji:"👨‍🍳", words:[
    { w:"boil", pos:"verb", d:"to cook in very hot water", ex:"Boil the eggs for ten minutes." },
    { w:"fry", pos:"verb", d:"to cook in hot oil", ex:"Fry the onions until they turn golden." },
    { w:"bake", pos:"verb", d:"to cook in an oven, like bread or cakes", ex:"We bake a chocolate cake every Friday." },
    { w:"grill", pos:"verb", d:"to cook over or under strong heat", ex:"Let's grill some kebabs in the garden." },
    { w:"roast", pos:"verb", d:"to cook meat or vegetables in an oven", ex:"They roast a whole chicken for the guests." },
    { w:"chop", pos:"verb", d:"to cut into small pieces with a knife", ex:"Chop the carrots into thin sticks." },
    { w:"slice", pos:"verb", d:"to cut into thin flat pieces", ex:"Slice the bread for the sandwiches." },
    { w:"mix", pos:"verb", d:"to put different things together", ex:"Mix the flour, eggs and milk in a bowl." },
    { w:"pour", pos:"verb", d:"to make liquid flow from one thing to another", ex:"Pour the tea slowly into the cups." },
    { w:"recipe", pos:"noun", d:"instructions for cooking a dish", ex:"This recipe needs only five ingredients." },
  ]},
  { id:38, title:"Eating out", emoji:"🍽️", words:[
    { w:"menu", pos:"noun", d:"the list of food in a restaurant", ex:"The waiter brought us the menu quickly." },
    { w:"waiter", pos:"noun", d:"a person who serves food in a restaurant", ex:"The waiter recommended the fish of the day." },
    { w:"order", pos:"verb", d:"to ask for food or drink in a restaurant", ex:"Are you ready to order your main course?" },
    { w:"starter", pos:"noun", d:"a small dish before the main meal", ex:"We chose soup as a starter." },
    { w:"dessert", pos:"noun", d:"sweet food eaten at the end of a meal", ex:"There is always room for dessert!" },
    { w:"bill", pos:"noun", d:"the paper showing how much you must pay", ex:"Could we have the bill, please?" },
    { w:"tip", pos:"noun", d:"extra money you give for good service", ex:"Dad left a generous tip for the waiter." },
    { w:"reserve", pos:"verb", d:"to book a table before you go", ex:"I want to reserve a table for six people." },
    { w:"takeaway", pos:"noun", d:"food you buy to eat at home", ex:"Let's get a takeaway and watch a film." },
    { w:"service", pos:"noun", d:"the way staff help customers", ex:"The food was great and the service was fast." },
  ]},
  { id:39, title:"Drinks", emoji:"🥤", words:[
    { w:"thirsty", pos:"adjective", d:"needing to drink something", ex:"Running makes me really thirsty." },
    { w:"juice", pos:"noun", d:"the liquid from fruit", ex:"She drinks fresh orange juice every morning." },
    { w:"fizzy", pos:"adjective", d:"full of little bubbles", ex:"Fizzy drinks are bad for your teeth." },
    { w:"lemonade", pos:"noun", d:"a sweet drink made with lemons", ex:"Cold lemonade is perfect on a hot day." },
    { w:"milkshake", pos:"noun", d:"a cold drink of milk mixed with fruit or ice cream", ex:"The cafe makes a great banana milkshake." },
    { w:"straw", pos:"noun", d:"a thin tube for drinking", ex:"The little girl drank her juice through a straw." },
    { w:"sip", pos:"verb", d:"to drink slowly in small amounts", ex:"She began to sip her hot tea carefully." },
    { w:"mug", pos:"noun", d:"a big cup with straight sides", ex:"A mug of warm milk helps me sleep." },
    { w:"jug", pos:"noun", d:"a container for pouring drinks", ex:"There is a jug of water on every table." },
    { w:"refreshing", pos:"adjective", d:"making you feel cool and full of energy", ex:"Mint tea is refreshing in summer." },
  ]},
]},

]};
