// CTN Vocab — Part 2: Free Time, Clothes & Shopping, School & Work, World & Nature
VOCAB.sections.push(

{ name:"Free Time", emoji:"🎮", units:[
  { id:40, title:"Free time", emoji:"🎨", words:[
    { w:"hobby", pos:"noun", d:"an activity you enjoy in your free time", ex:"Photography is my favourite hobby." },
    { w:"leisure", pos:"noun", d:"time when you are not working or studying", ex:"Swimming is a popular leisure activity." },
    { w:"relax", pos:"verb", d:"to rest and feel calm", ex:"I relax by listening to quiet music." },
    { w:"collect", pos:"verb", d:"to keep many things of one kind", ex:"My brother likes to collect coins from different countries." },
    { w:"photography", pos:"noun", d:"the art of taking pictures", ex:"She studies photography at the weekend club." },
    { w:"gardening", pos:"noun", d:"growing and caring for plants", ex:"Grandma finds gardening very peaceful." },
    { w:"chess", pos:"noun", d:"a board game for two players with kings and queens", ex:"He won the school chess tournament." },
    { w:"camping", pos:"noun", d:"sleeping outside in a tent for fun", ex:"We went camping by the mountain lake." },
    { w:"puzzle", pos:"noun", d:"a game with pieces you put together", ex:"This puzzle has one thousand pieces." },
    { w:"spare time", pos:"noun", d:"free time when you have nothing you must do", ex:"What do you do in your spare time?" },
  ]},
  { id:44, title:"Film and cinema", emoji:"🎬", words:[
    { w:"comedy", pos:"noun", d:"a funny film that makes you laugh", ex:"We laughed all through the comedy." },
    { w:"horror", pos:"noun", d:"a film made to frighten you", ex:"I never watch horror films alone." },
    { w:"thriller", pos:"noun", d:"an exciting film full of action and surprises", ex:"The thriller kept us guessing until the end." },
    { w:"cartoon", pos:"noun", d:"a film with drawn or animated pictures", ex:"My little sister watches the same cartoon daily." },
    { w:"actor", pos:"noun", d:"a person who plays a role in films", ex:"The main actor learned to ride a horse." },
    { w:"director", pos:"noun", d:"the person who makes decisions about a film", ex:"The director shouted action and filming began." },
    { w:"scene", pos:"noun", d:"one part of a film", ex:"The last scene made everyone cry." },
    { w:"subtitles", pos:"noun", d:"words on the screen that translate the film", ex:"We watched the film with English subtitles." },
    { w:"plot", pos:"noun", d:"the story of a film or book", ex:"The plot was full of clever surprises." },
    { w:"review", pos:"noun", d:"an opinion piece about a film", ex:"The new film got a five-star review." },
  ]},
  { id:46, title:"Music", emoji:"🎵", words:[
    { w:"singer", pos:"noun", d:"a person who sings", ex:"The singer taught the crowd her new song." },
    { w:"band", pos:"noun", d:"a group of musicians who play together", ex:"His band practises in the garage." },
    { w:"concert", pos:"noun", d:"a live show of music", ex:"Thousands of fans came to the concert." },
    { w:"stage", pos:"noun", d:"the platform where musicians perform", ex:"She felt nervous walking onto the stage." },
    { w:"audience", pos:"noun", d:"the people watching a show", ex:"The audience clapped for five minutes." },
    { w:"rhythm", pos:"noun", d:"the regular beat of music", ex:"Everyone danced to the rhythm of the drums." },
    { w:"lyrics", pos:"noun", d:"the words of a song", ex:"I know the lyrics of every song on this album." },
    { w:"drums", pos:"noun", d:"instruments you hit to make a beat", ex:"My neighbour plays the drums too loudly." },
    { w:"violin", pos:"noun", d:"a wooden instrument played with a bow", ex:"She has played the violin since she was five." },
    { w:"perform", pos:"verb", d:"to sing, play or act for people", ex:"The students will perform at the school party." },
  ]},
  { id:47, title:"Sport", emoji:"🎾", words:[
    { w:"court", pos:"noun", d:"the marked area where you play tennis or basketball", ex:"The players shook hands on the court." },
    { w:"racket", pos:"noun", d:"the thing you hold to hit the ball in tennis", ex:"He bought a new racket for the season." },
    { w:"net", pos:"noun", d:"the material stretched across the middle of a court", ex:"The ball touched the net and fell back." },
    { w:"serve", pos:"verb", d:"to start play by hitting the ball first", ex:"She can serve faster than her coach." },
    { w:"coach", pos:"noun", d:"a person who trains sports players", ex:"Our coach makes us run every morning." },
    { w:"champion", pos:"noun", d:"the winner of a competition", ex:"The young champion lifted the golden cup." },
    { w:"tournament", pos:"noun", d:"a competition with many matches", ex:"Sixteen teams entered the summer tournament." },
    { w:"score", pos:"noun", d:"the number of points in a game", ex:"The final score was three points to two." },
    { w:"opponent", pos:"noun", d:"the person you play against", ex:"Always shake hands with your opponent." },
    { w:"train", pos:"verb", d:"to practise a sport regularly", ex:"They train twice a week after school." },
  ]},
  { id:48, title:"Football", emoji:"⚽", words:[
    { w:"pitch", pos:"noun", d:"the grass field where football is played", ex:"The players ran onto the pitch together." },
    { w:"goalkeeper", pos:"noun", d:"the player who guards the goal", ex:"The goalkeeper jumped and caught the ball." },
    { w:"defender", pos:"noun", d:"a player who stops the other team scoring", ex:"The defender kicked the ball away just in time." },
    { w:"referee", pos:"noun", d:"the person who controls the match", ex:"The referee showed the player a yellow card." },
    { w:"penalty", pos:"noun", d:"a free kick at the goal after a foul", ex:"He scored the winning penalty in the final." },
    { w:"kick", pos:"verb", d:"to hit something with your foot", ex:"She can kick the ball across the whole pitch." },
    { w:"pass", pos:"verb", d:"to send the ball to a teammate", ex:"Pass the ball quickly and keep moving." },
    { w:"tackle", pos:"verb", d:"to take the ball from another player", ex:"He learned to tackle without pushing." },
    { w:"crowd", pos:"noun", d:"the large group of fans watching", ex:"The crowd sang songs for ninety minutes." },
    { w:"draw", pos:"noun", d:"a result where both teams have equal points", ex:"The match ended in a boring goalless draw." },
  ]},
]},

{ name:"Clothes & Shopping", emoji:"🛍️", units:[
  { id:10, title:"Clothes", emoji:"👕", words:[
    { w:"jacket", pos:"noun", d:"a short coat", ex:"Take your jacket, it is windy outside." },
    { w:"jumper", pos:"noun", d:"a warm knitted top", ex:"Grandma knitted me a woollen jumper." },
    { w:"trousers", pos:"noun", d:"clothing that covers your legs", ex:"These trousers are too long for me." },
    { w:"skirt", pos:"noun", d:"clothing that hangs from the waist", ex:"Her school skirt is dark blue." },
    { w:"socks", pos:"noun", d:"soft clothing for your feet", ex:"I always lose one of my socks." },
    { w:"scarf", pos:"noun", d:"cloth you wear around your neck", ex:"Wrap your scarf tightly, it is freezing." },
    { w:"gloves", pos:"noun", d:"clothing for your hands with separate fingers", ex:"She forgot her gloves on the bus." },
    { w:"belt", pos:"noun", d:"a band you wear around your waist", ex:"He needs a belt for these loose jeans." },
    { w:"button", pos:"noun", d:"a small round thing that closes clothes", ex:"A button fell off my school shirt." },
    { w:"pocket", pos:"noun", d:"a small bag sewn into clothes", ex:"He keeps his keys in his back pocket." },
  ]},
  { id:11, title:"Talking about clothes", emoji:"👗", words:[
    { w:"fashionable", pos:"adjective", d:"popular in style right now", ex:"White trainers are fashionable this year." },
    { w:"casual", pos:"adjective", d:"comfortable, not formal", ex:"Friday is a casual clothes day at work." },
    { w:"smart", pos:"adjective", d:"clean, tidy and formal", ex:"He looked smart in his new suit." },
    { w:"tight", pos:"adjective", d:"fitting very close to your body", ex:"These shoes are too tight for my feet." },
    { w:"loose", pos:"adjective", d:"not fitting close to your body", ex:"He likes loose T-shirts in summer." },
    { w:"suit", pos:"verb", d:"to look good on someone", ex:"Dark colours suit you very well." },
    { w:"match", pos:"verb", d:"to look good together", ex:"Your socks do not match your shoes." },
    { w:"try on", pos:"phrasal verb", d:"to put clothes on to test them", ex:"Can I try on this jacket in medium?" },
    { w:"size", pos:"noun", d:"how big or small clothing is", ex:"Do you have these boots in size forty?" },
    { w:"fit", pos:"verb", d:"to be the right size for you", ex:"These trousers fit me perfectly." },
  ]},
  { id:60, title:"Shops and shopping", emoji:"🛒", words:[
    { w:"customer", pos:"noun", d:"a person who buys things in a shop", ex:"The shop gives every customer a small gift." },
    { w:"discount", pos:"noun", d:"a lower price than usual", ex:"Students get a ten percent discount here." },
    { w:"receipt", pos:"noun", d:"the paper that proves you paid", ex:"Keep the receipt in case you return it." },
    { w:"refund", pos:"noun", d:"money given back for returned goods", ex:"The broken toy got a full refund." },
    { w:"bargain", pos:"noun", d:"something good bought at a low price", ex:"This coat was a real bargain in the sale." },
    { w:"queue", pos:"noun", d:"a line of people waiting", ex:"There was a long queue at the checkout." },
    { w:"cashier", pos:"noun", d:"the person who takes your money in a shop", ex:"The cashier counted my change carefully." },
    { w:"afford", pos:"verb", d:"to have enough money to buy something", ex:"I cannot afford the newest phone." },
    { w:"spend", pos:"verb", d:"to use money to buy things", ex:"I spend my pocket money on books and stickers." },
    { w:"wallet", pos:"noun", d:"a small case for money and cards", ex:"He left his wallet at home again." },
  ]},
  { id:58, title:"Money", emoji:"💰", words:[
    { w:"wealthy", pos:"adjective", d:"having a lot of money", ex:"The wealthy businessman built a new school." },
    { w:"poverty", pos:"noun", d:"the state of being very poor", ex:"The charity helps families living in poverty." },
    { w:"earn", pos:"verb", d:"to get money for work you do", ex:"You can earn extra money by teaching online." },
    { w:"save", pos:"verb", d:"to keep money to use later", ex:"I save half of my pocket money every week." },
    { w:"waste", pos:"verb", d:"to use money or time badly", ex:"Do not waste your money on silly games." },
    { w:"borrow", pos:"verb", d:"to take something you will give back", ex:"Can I borrow ten thousand som until Friday?" },
    { w:"lend", pos:"verb", d:"to give something that will come back to you", ex:"My brother agreed to lend me his bike." },
    { w:"coin", pos:"noun", d:"a piece of metal money", ex:"He found an old silver coin in the garden." },
    { w:"banknote", pos:"noun", d:"a piece of paper money", ex:"The machine does not accept this old banknote." },
    { w:"millionaire", pos:"noun", d:"a person who has a million or more", ex:"The millionaire gave his money to hospitals." },
  ]},
  { id:54, title:"Telephones", emoji:"📱", words:[
    { w:"mobile", pos:"noun", d:"a phone you carry with you", ex:"Turn off your mobile during the lesson." },
    { w:"message", pos:"noun", d:"words you send to someone", ex:"Send me a message when you arrive." },
    { w:"ring", pos:"verb", d:"to call someone on the phone", ex:"I will ring you after dinner." },
    { w:"dial", pos:"verb", d:"to press the numbers to call", ex:"Dial this number and ask for the manager." },
    { w:"voicemail", pos:"noun", d:"recorded messages left for you", ex:"He left a long voicemail about the meeting." },
    { w:"charger", pos:"noun", d:"the cable that gives a phone power", ex:"My battery died and I forgot my charger." },
    { w:"screen", pos:"noun", d:"the flat part of a phone you look at", ex:"The screen cracked when the phone fell." },
    { w:"contact", pos:"noun", d:"a person's number saved in your phone", ex:"Add me as a contact in your phone." },
    { w:"hang up", pos:"phrasal verb", d:"to end a phone call", ex:"Do not hang up, I need one more minute." },
    { w:"call back", pos:"phrasal verb", d:"to phone someone again later", ex:"She is busy now but will call back soon." },
  ]},
]},

{ name:"School & Work", emoji:"🎓", units:[
  { id:67, title:"School", emoji:"🏫", words:[
    { w:"subject", pos:"noun", d:"something you study, like maths or history", ex:"English is my favourite subject at school." },
    { w:"timetable", pos:"noun", d:"the plan of lessons for the week", ex:"Check the timetable for tomorrow's lessons." },
    { w:"uniform", pos:"noun", d:"the special clothes worn at school", ex:"Our school uniform is white and navy." },
    { w:"homework", pos:"noun", d:"school work you do at home", ex:"Finish your homework before playing games." },
    { w:"break", pos:"noun", d:"free time between lessons", ex:"We play football during the lunch break." },
    { w:"mark", pos:"noun", d:"the number or letter showing your result", ex:"She got the highest mark in the test." },
    { w:"exam", pos:"noun", d:"an important test of what you know", ex:"The final exam is in two weeks." },
    { w:"playground", pos:"noun", d:"the outside area where children play", ex:"The playground is full at break time." },
    { w:"term", pos:"noun", d:"one of the parts of the school year", ex:"The autumn term ends in December." },
    { w:"absent", pos:"adjective", d:"not at school or work", ex:"Three students were absent because of flu." },
  ]},
  { id:69, title:"Learning a language", emoji:"🗣️", words:[
    { w:"vocabulary", pos:"noun", d:"all the words you know in a language", ex:"Reading builds your vocabulary faster than anything." },
    { w:"grammar", pos:"noun", d:"the rules of a language", ex:"English grammar is easier than Russian grammar." },
    { w:"pronunciation", pos:"noun", d:"the way words are spoken", ex:"Her pronunciation improved after watching films." },
    { w:"fluent", pos:"adjective", d:"able to speak easily and smoothly", ex:"He became fluent in English in three years." },
    { w:"accent", pos:"noun", d:"the way people from a place sound", ex:"She speaks English with a beautiful British accent." },
    { w:"translate", pos:"verb", d:"to change words into another language", ex:"Can you translate this song for me?" },
    { w:"practise", pos:"verb", d:"to do something many times to improve", ex:"We practise speaking English every single day." },
    { w:"improve", pos:"verb", d:"to become better at something", ex:"Your writing will improve if you read more." },
    { w:"mistake", pos:"noun", d:"something done wrongly", ex:"Do not be afraid of making a mistake." },
    { w:"bilingual", pos:"adjective", d:"able to speak two languages", ex:"Their children are bilingual in Uzbek and English." },
  ]},
  { id:70, title:"Jobs", emoji:"👷", words:[
    { w:"nurse", pos:"noun", d:"a person who cares for sick people", ex:"The nurse checked his temperature kindly." },
    { w:"engineer", pos:"noun", d:"a person who designs machines or buildings", ex:"The engineer drew plans for the new bridge." },
    { w:"lawyer", pos:"noun", d:"a person who helps people with the law", ex:"The lawyer explained the contract clearly." },
    { w:"firefighter", pos:"noun", d:"a person who puts out fires", ex:"A brave firefighter rescued the cat." },
    { w:"plumber", pos:"noun", d:"a person who fixes water pipes", ex:"The plumber repaired the leaking tap." },
    { w:"electrician", pos:"noun", d:"a person who works with electrical wires", ex:"An electrician fixed the lights in our class." },
    { w:"accountant", pos:"noun", d:"a person who works with money records", ex:"The accountant checks the numbers every month." },
    { w:"journalist", pos:"noun", d:"a person who writes news stories", ex:"The journalist interviewed the young champion." },
    { w:"chef", pos:"noun", d:"a professional cook", ex:"The chef created a new dessert for the menu." },
    { w:"vet", pos:"noun", d:"a doctor for animals", ex:"We took our puppy to the vet for a check." },
  ]},
  { id:94, title:"Time", emoji:"⏰", words:[
    { w:"century", pos:"noun", d:"a period of one hundred years", ex:"This mosque was built in the fifteenth century." },
    { w:"decade", pos:"noun", d:"a period of ten years", ex:"Phones changed a lot in the last decade." },
    { w:"fortnight", pos:"noun", d:"a period of two weeks", ex:"We are going on holiday for a fortnight." },
    { w:"midnight", pos:"noun", d:"twelve o'clock at night", ex:"The new year begins exactly at midnight." },
    { w:"midday", pos:"noun", d:"twelve o'clock in the day", ex:"The sun is strongest at midday." },
    { w:"calendar", pos:"noun", d:"a chart showing days and months", ex:"Circle the exam date on the calendar." },
    { w:"deadline", pos:"noun", d:"the last time something must be finished", ex:"The deadline for the project is Friday." },
    { w:"punctual", pos:"adjective", d:"always arriving on time", ex:"Our teacher is punctual to the minute." },
    { w:"immediately", pos:"adverb", d:"right now, without waiting", ex:"Call the doctor immediately if the fever rises." },
    { w:"recently", pos:"adverb", d:"a short time ago", ex:"They recently moved to a bigger flat." },
  ]},
  { id:95, title:"Numbers", emoji:"🔢", words:[
    { w:"dozen", pos:"noun", d:"a group of twelve", ex:"Mum bought a dozen eggs at the bazaar." },
    { w:"half", pos:"noun", d:"one of two equal parts", ex:"He gave half of his sandwich to me." },
    { w:"quarter", pos:"noun", d:"one of four equal parts", ex:"A quarter of the students walk to school." },
    { w:"double", pos:"verb", d:"to become two times bigger", ex:"The city's population may double in fifty years." },
    { w:"triple", pos:"verb", d:"to become three times bigger", ex:"The team hopes to triple their score next season." },
    { w:"average", pos:"noun", d:"the middle or usual amount", ex:"The average of two and four is three." },
    { w:"approximately", pos:"adverb", d:"about, not exactly", ex:"The journey takes approximately two hours." },
    { w:"odd", pos:"adjective", d:"a number that cannot be divided by two", ex:"One, three and five are odd numbers." },
    { w:"even", pos:"adjective", d:"a number that can be divided by two", ex:"All even numbers end in special digits." },
    { w:"percentage", pos:"noun", d:"an amount out of one hundred", ex:"What percentage of the test did you get right?" },
  ]},
]},

{ name:"World & Nature", emoji:"🌍", units:[
  { id:88, title:"The weather", emoji:"🌤️", words:[
    { w:"forecast", pos:"noun", d:"a report saying what the weather will be", ex:"The forecast says snow is coming tomorrow." },
    { w:"sunshine", pos:"noun", d:"the light and heat from the sun", ex:"The cat stretched out in the warm sunshine." },
    { w:"breeze", pos:"noun", d:"a light gentle wind", ex:"A cool breeze came from the mountains." },
    { w:"storm", pos:"noun", d:"very bad weather with wind and rain", ex:"The storm broke branches off the trees." },
    { w:"thunder", pos:"noun", d:"the loud sound during a storm", ex:"Thunder shook the windows all night." },
    { w:"lightning", pos:"noun", d:"the flash of light in a storm", ex:"Lightning lit up the whole sky." },
    { w:"fog", pos:"noun", d:"thick cloud near the ground", ex:"We could not see the road in the fog." },
    { w:"frost", pos:"noun", d:"ice crystals that form on cold nights", ex:"The grass was white with morning frost." },
    { w:"rainbow", pos:"noun", d:"the colourful arc in the sky after rain", ex:"A beautiful rainbow appeared after the storm." },
    { w:"temperature", pos:"noun", d:"how hot or cold something is", ex:"The temperature dropped below zero last night." },
  ]},
  { id:90, title:"Wild animals", emoji:"🦁", words:[
    { w:"tiger", pos:"noun", d:"a big wild cat with orange and black stripes", ex:"The tiger moved silently through the grass." },
    { w:"wolf", pos:"noun", d:"a wild animal like a large dog", ex:"A lone wolf howled in the mountains." },
    { w:"bear", pos:"noun", d:"a large strong animal with thick fur", ex:"The bear caught a fish in the river." },
    { w:"eagle", pos:"noun", d:"a large bird that hunts", ex:"An eagle circled high above the valley." },
    { w:"snake", pos:"noun", d:"a long animal with no legs", ex:"The snake slid quietly under a rock." },
    { w:"monkey", pos:"noun", d:"a clever animal that climbs trees", ex:"The monkey stole a banana from my bag!" },
    { w:"giraffe", pos:"noun", d:"the tallest animal with a very long neck", ex:"A giraffe can eat leaves from the highest branches." },
    { w:"crocodile", pos:"noun", d:"a large reptile with strong jaws", ex:"The crocodile waited silently in the river." },
    { w:"dolphin", pos:"noun", d:"a friendly clever sea animal", ex:"A dolphin jumped beside our boat." },
    { w:"whale", pos:"noun", d:"the biggest animal in the ocean", ex:"The blue whale is bigger than any dinosaur." },
  ]},
  { id:91, title:"Farm animals", emoji:"🐄", words:[
    { w:"goat", pos:"noun", d:"a farm animal with horns that eats everything", ex:"The goat ate my homework, honestly!" },
    { w:"sheep", pos:"noun", d:"a farm animal kept for wool", ex:"The sheep followed the farmer up the hill." },
    { w:"lamb", pos:"noun", d:"a young sheep", ex:"The lamb stayed close to its mother." },
    { w:"donkey", pos:"noun", d:"an animal like a small horse with long ears", ex:"The donkey carried water up the mountain." },
    { w:"duck", pos:"noun", d:"a water bird from the farm", ex:"The duck led her babies to the pond." },
    { w:"goose", pos:"noun", d:"a large water bird with a long neck", ex:"The goose chased the postman across the yard." },
    { w:"turkey", pos:"noun", d:"a large farm bird", ex:"The turkey is the proudest bird on the farm." },
    { w:"rabbit", pos:"noun", d:"a small animal with long ears", ex:"The rabbit disappeared into its hole." },
    { w:"rooster", pos:"noun", d:"a male chicken that crows in the morning", ex:"The rooster wakes the village at sunrise." },
    { w:"stable", pos:"noun", d:"a building where horses live", ex:"She cleans the stable before breakfast." },
  ]},
  { id:93, title:"Towns and cities", emoji:"🏙️", words:[
    { w:"crossroads", pos:"noun", d:"a place where two roads meet", ex:"Turn left at the next crossroads." },
    { w:"pavement", pos:"noun", d:"the path beside the road for walking", ex:"Keep your bike off the pavement, please." },
    { w:"square", pos:"noun", d:"an open area in the middle of a town", ex:"People gathered in the square for the festival." },
    { w:"bridge", pos:"noun", d:"a structure that crosses a river or road", ex:"The old bridge is only for walkers now." },
    { w:"fountain", pos:"noun", d:"a structure that shoots water into the air", ex:"Children played near the singing fountain." },
    { w:"statue", pos:"noun", d:"a stone or metal figure of a person", ex:"A statue of the poet stands in the park." },
    { w:"suburb", pos:"noun", d:"an area of homes outside the city centre", ex:"They moved to a quiet suburb last year." },
    { w:"traffic", pos:"noun", d:"all the cars moving on the roads", ex:"Heavy traffic made everyone late today." },
    { w:"crowded", pos:"adjective", d:"full of too many people", ex:"The bazaar is crowded on Sunday mornings." },
    { w:"roundabout", pos:"noun", d:"a circle where roads meet", ex:"Take the second exit at the roundabout." },
  ]},
  { id:82, title:"The environment", emoji:"🌳", words:[
    { w:"pollution", pos:"noun", d:"dirt and harm in air, water or land", ex:"Air pollution is worse in big cities." },
    { w:"recycle", pos:"verb", d:"to use old things to make new ones", ex:"We recycle paper, glass and plastic at school." },
    { w:"rubbish", pos:"noun", d:"things you throw away", ex:"Put your rubbish in the bin, not the street." },
    { w:"climate", pos:"noun", d:"the usual weather of a place", ex:"The climate here is hot and dry in summer." },
    { w:"litter", pos:"noun", d:"rubbish left on the ground in public", ex:"Volunteers picked up litter in the park." },
    { w:"protect", pos:"verb", d:"to keep something safe", ex:"We must protect the rivers and lakes." },
    { w:"destroy", pos:"verb", d:"to damage something completely", ex:"Fires can destroy a forest in hours." },
    { w:"planet", pos:"noun", d:"a world in space, like Earth", ex:"Earth is the only planet with chocolate!" },
    { w:"wildlife", pos:"noun", d:"animals and plants living in nature", ex:"The national park protects rare wildlife." },
    { w:"renewable", pos:"adjective", d:"able to be used again and again, like sun power", ex:"Solar energy is clean and renewable." },
  ]},
  { id:87, title:"Countries and nationalities", emoji:"🗺️", words:[
    { w:"nationality", pos:"noun", d:"belonging to a particular country", ex:"What nationality is your new classmate?" },
    { w:"foreign", pos:"adjective", d:"from another country", ex:"She collects coins from foreign countries." },
    { w:"abroad", pos:"adverb", d:"in or to another country", ex:"My sister is studying abroad in London." },
    { w:"border", pos:"noun", d:"the line between two countries", ex:"We crossed the border early in the morning." },
    { w:"capital", pos:"noun", d:"the main city of a country", ex:"Tashkent is the capital of Uzbekistan." },
    { w:"flag", pos:"noun", d:"the special cloth symbol of a country", ex:"Every flag tells a story about its country." },
    { w:"citizen", pos:"noun", d:"an official member of a country", ex:"Every citizen has rights and duties." },
    { w:"culture", pos:"noun", d:"the traditions and way of life of a people", ex:"Uzbek culture is famous for its hospitality." },
    { w:"tradition", pos:"noun", d:"something special passed down for years", ex:"Making sumalak in spring is a beautiful tradition." },
    { w:"passport", pos:"noun", d:"the official document for travelling", ex:"Check your passport before going to the airport." },
  ]},
]}

);
