// CTN Vocab — Part 3: People+, Emotions & Love, Body & Health+, Home+, Food+, Free Time+, Shopping+, School & Work+
(function(){
const sec = n => VOCAB.sections.find(s=>s.name===n);

sec("People").units.push(
  { id:3, title:"Babies and children", emoji:"👶", words:[
    { w:"pram", pos:"noun", d:"a small vehicle for pushing a baby", ex:"Mum pushed the pram around the park." },
    { w:"cot", pos:"noun", d:"a small bed with sides for a baby", ex:"The baby slept quietly in her cot." },
    { w:"crawl", pos:"verb", d:"to move on your hands and knees", ex:"The baby can crawl across the whole room." },
    { w:"nappy", pos:"noun", d:"the cloth a baby wears before using a toilet", ex:"Dad learned to change a nappy very fast." },
    { w:"naughty", pos:"adjective", d:"behaving badly", ex:"The naughty puppy ate my little brother's sock." },
    { w:"obedient", pos:"adjective", d:"always doing what you are told", ex:"Their obedient son tidies his toys himself." },
    { w:"spoil", pos:"verb", d:"to give a child everything they want", ex:"Grandparents love to spoil their grandchildren." },
    { w:"look after", pos:"phrasal verb", d:"to take care of someone", ex:"Can you look after my little sister today?" },
    { w:"playful", pos:"adjective", d:"full of fun and games", ex:"The playful kitten chased the ball of wool." },
    { w:"lullaby", pos:"noun", d:"a soft song that helps a baby sleep", ex:"She sang a sweet lullaby every night." },
  ]},
  { id:9, title:"Appearance", emoji:"👀", words:[
    { w:"handsome", pos:"adjective", d:"good looking, usually used for men", ex:"The handsome actor smiled for the cameras." },
    { w:"gorgeous", pos:"adjective", d:"extremely beautiful", ex:"You look gorgeous in that traditional dress." },
    { w:"attractive", pos:"adjective", d:"nice to look at", ex:"The old town has many attractive buildings." },
    { w:"slim", pos:"adjective", d:"thin in a healthy, nice way", ex:"She stays slim by swimming twice a week." },
    { w:"skinny", pos:"adjective", d:"very thin, maybe too thin", ex:"The skinny cat needed a good meal." },
    { w:"overweight", pos:"adjective", d:"heavier than is healthy", ex:"The vet said the dog was a little overweight." },
    { w:"bald", pos:"adjective", d:"having no hair on your head", ex:"My uncle went bald at thirty." },
    { w:"curly", pos:"adjective", d:"hair with lots of curls", ex:"Her curly hair takes an hour to brush." },
    { w:"freckles", pos:"noun", d:"small brown spots on the skin", ex:"In summer her nose gets covered in freckles." },
    { w:"scar", pos:"noun", d:"a mark left on skin after a cut heals", ex:"He has a small scar above his eyebrow." },
  ]},
  { id:13, title:"Describing people", emoji:"🌟", words:[
    { w:"ambitious", pos:"adjective", d:"wanting very much to succeed", ex:"The ambitious student dreams of studying at Oxford." },
    { w:"sensible", pos:"adjective", d:"making good, careful decisions", ex:"Be sensible and take an umbrella today." },
    { w:"sensitive", pos:"adjective", d:"easily hurt by words or events", ex:"She is sensitive about her drawing skills." },
    { w:"reliable", pos:"adjective", d:"always doing what you promise", ex:"A reliable friend never forgets your birthday." },
    { w:"stubborn", pos:"adjective", d:"refusing to change your mind", ex:"The stubborn goat would not move from the road." },
    { w:"talkative", pos:"adjective", d:"loving to talk a lot", ex:"My talkative cousin never stops asking questions." },
    { w:"creative", pos:"adjective", d:"full of new ideas", ex:"The creative pupils painted the classroom door." },
    { w:"curious", pos:"adjective", d:"wanting to know about everything", ex:"Cats are curious about every open box." },
    { w:"brave", pos:"adjective", d:"not afraid of danger", ex:"The brave girl saved the kitten from the tree." },
    { w:"rude", pos:"adjective", d:"not polite", ex:"It is rude to talk with your mouth full." },
  ]}
);

VOCAB.sections.splice(1, 0, { name:"Emotions & Love", emoji:"💞", units:[
  { id:15, title:"Happy or sad", emoji:"😄", words:[
    { w:"delighted", pos:"adjective", d:"extremely pleased", ex:"She was delighted with her exam results." },
    { w:"thrilled", pos:"adjective", d:"very excited and happy", ex:"He was thrilled to meet his favourite player." },
    { w:"glad", pos:"adjective", d:"pleased about something", ex:"I am glad you came to the party." },
    { w:"joyful", pos:"adjective", d:"full of happiness", ex:"The wedding was a joyful celebration." },
    { w:"miserable", pos:"adjective", d:"very unhappy", ex:"The cold rainy weather makes him miserable." },
    { w:"gloomy", pos:"adjective", d:"sad and without hope; dark", ex:"Why the gloomy face on such a sunny day?" },
    { w:"tearful", pos:"adjective", d:"almost crying", ex:"She said a tearful goodbye at the airport." },
    { w:"mood", pos:"noun", d:"the way you feel at a moment", ex:"Music always puts me in a good mood." },
    { w:"sob", pos:"verb", d:"to cry loudly with short breaths", ex:"The little boy began to sob over his broken toy." },
    { w:"cheer up", pos:"phrasal verb", d:"to become or make someone happier", ex:"Let's cheer up Grandma with some flowers." },
  ]},
  { id:16, title:"Getting angry", emoji:"😠", words:[
    { w:"furious", pos:"adjective", d:"extremely angry", ex:"Dad was furious when the window broke." },
    { w:"annoyed", pos:"adjective", d:"a little angry", ex:"She gets annoyed when people are late." },
    { w:"irritated", pos:"adjective", d:"annoyed by something that keeps happening", ex:"The buzzing fly made everyone irritated." },
    { w:"temper", pos:"noun", d:"how quickly you get angry", ex:"Try to control your temper during the game." },
    { w:"frustrated", pos:"adjective", d:"angry because you cannot do something", ex:"He felt frustrated with the difficult puzzle." },
    { w:"offended", pos:"adjective", d:"hurt by something rude", ex:"She was offended by his joke." },
    { w:"insult", pos:"verb", d:"to say something rude to someone", ex:"Never insult your opponent after a match." },
    { w:"shout", pos:"verb", d:"to speak very loudly", ex:"There is no need to shout, I can hear you." },
    { w:"slam", pos:"verb", d:"to close something loudly and with force", ex:"Please do not slam the door." },
    { w:"forgive", pos:"verb", d:"to stop being angry with someone", ex:"True friends forgive each other quickly." },
  ]},
  { id:17, title:"Liking and disliking", emoji:"💙", words:[
    { w:"adore", pos:"verb", d:"to love very much", ex:"The children adore their new puppy." },
    { w:"admire", pos:"verb", d:"to respect and look up to", ex:"I admire people who learn three languages." },
    { w:"prefer", pos:"verb", d:"to like one thing more than another", ex:"I prefer green tea to black tea." },
    { w:"fancy", pos:"verb", d:"to want something; to find attractive", ex:"Do you fancy an ice cream after school?" },
    { w:"keen", pos:"adjective", d:"very interested in something", ex:"He is keen on chess and photography." },
    { w:"fond", pos:"adjective", d:"liking someone or something a lot", ex:"She is fond of her grandmother's stories." },
    { w:"dislike", pos:"verb", d:"to not like", ex:"Many kids dislike the smell of onions." },
    { w:"favourite", pos:"adjective", d:"liked more than all others", ex:"Plov is my favourite dish in the world." },
    { w:"attract", pos:"verb", d:"to make someone interested", ex:"Bright flowers attract bees and butterflies." },
    { w:"appeal", pos:"verb", d:"to seem interesting or nice", ex:"Camping does not appeal to my mother." },
  ]},
  { id:7, title:"Love and romance", emoji:"💘", words:[
    { w:"romantic", pos:"adjective", d:"showing love, like flowers and candles", ex:"They had a romantic dinner by the river." },
    { w:"date", pos:"noun", d:"a planned meeting between two people in love", ex:"Their first date was at a small cafe." },
    { w:"couple", pos:"noun", d:"two people who are together", ex:"The young couple walked hand in hand." },
    { w:"propose", pos:"verb", d:"to ask someone to marry you", ex:"He chose the mountain top to propose." },
    { w:"valentine", pos:"noun", d:"the person you love on the fourteenth of February", ex:"She received a card from a secret valentine." },
    { w:"heartbroken", pos:"adjective", d:"very sad because love ended", ex:"He was heartbroken when she moved abroad." },
    { w:"hug", pos:"noun", d:"holding someone in your arms", ex:"Give your mother a big hug every morning." },
    { w:"kiss", pos:"noun", d:"a touch with your lips to show love", ex:"Grandma gave each child a kiss goodnight." },
    { w:"soulmate", pos:"noun", d:"the person perfect for you", ex:"Grandpa still calls Grandma his soulmate." },
    { w:"anniversary", pos:"noun", d:"the yearly date of a special event", ex:"They celebrate their anniversary every spring." },
  ]},
  { id:8, title:"Marriage", emoji:"💍", words:[
    { w:"wedding", pos:"noun", d:"the ceremony when two people marry", ex:"Three hundred guests came to the wedding." },
    { w:"bride", pos:"noun", d:"the woman getting married", ex:"The bride wore a beautiful white dress." },
    { w:"groom", pos:"noun", d:"the man getting married", ex:"The nervous groom kept checking his watch." },
    { w:"honeymoon", pos:"noun", d:"the holiday after a wedding", ex:"They spent their honeymoon in Samarkand." },
    { w:"ceremony", pos:"noun", d:"a formal event with traditions", ex:"The ceremony started exactly at noon." },
    { w:"invitation", pos:"noun", d:"a card asking you to come to an event", ex:"We received a golden invitation to the wedding." },
    { w:"celebrate", pos:"verb", d:"to do something fun for a special day", ex:"Let's celebrate your results with a cake." },
    { w:"reception", pos:"noun", d:"the party after a wedding ceremony", ex:"The reception went on until midnight." },
    { w:"divorce", pos:"noun", d:"the legal end of a marriage", ex:"Divorce is always hard for a family." },
    { w:"congratulate", pos:"verb", d:"to tell someone you are happy for them", ex:"Everyone came to congratulate the new couple." },
  ]},
  { id:4, title:"Life and death", emoji:"🕊️", words:[
    { w:"alive", pos:"adjective", d:"living, not dead", ex:"The old tree is still alive after two hundred years." },
    { w:"funeral", pos:"noun", d:"the ceremony after someone dies", ex:"The whole village came to the funeral." },
    { w:"grave", pos:"noun", d:"the place where a dead person is buried", ex:"They put fresh flowers on the grave." },
    { w:"widow", pos:"noun", d:"a woman whose husband has died", ex:"The kind widow feeds all the street cats." },
    { w:"orphan", pos:"noun", d:"a child whose parents have died", ex:"The orphan found a loving new family." },
    { w:"inherit", pos:"verb", d:"to receive something from someone who died", ex:"She will inherit her grandmother's ring." },
    { w:"memory", pos:"noun", d:"something you remember", ex:"My clearest memory is our trip to the sea." },
    { w:"miss", pos:"verb", d:"to feel sad because someone is not there", ex:"We all miss our old teacher." },
    { w:"condolences", pos:"noun", d:"words of sympathy when someone dies", ex:"He sent his condolences to the family." },
    { w:"peaceful", pos:"adjective", d:"calm and quiet", ex:"The old man had a long and peaceful life." },
  ]},
]});

sec("Body & Health").units.push(
  { id:19, title:"Hair", emoji:"💇", words:[
    { w:"fringe", pos:"noun", d:"hair cut short over the forehead", ex:"Her new fringe covers her eyebrows." },
    { w:"ponytail", pos:"noun", d:"hair tied together at the back", ex:"She wears a ponytail for volleyball practice." },
    { w:"plait", pos:"verb", d:"to twist hair into a rope shape", ex:"Grandma taught me to plait my sister's hair." },
    { w:"blonde", pos:"adjective", d:"with light yellow hair", ex:"The blonde girl sits in the front row." },
    { w:"wavy", pos:"adjective", d:"hair with soft curves", ex:"His wavy hair never stays neat." },
    { w:"dye", pos:"verb", d:"to change the colour of hair", ex:"She wants to dye her hair blue!" },
    { w:"haircut", pos:"noun", d:"the act or style of cutting hair", ex:"You need a haircut before the ceremony." },
    { w:"hairdresser", pos:"noun", d:"a person whose job is cutting hair", ex:"The hairdresser suggested a shorter style." },
    { w:"shave", pos:"verb", d:"to remove hair with a razor", ex:"Dad forgot to shave before the meeting." },
    { w:"comb", pos:"verb", d:"to make hair tidy with a toothed tool", ex:"Comb your hair before the photo." },
  ]},
  { id:21, title:"Body movements", emoji:"🤸", words:[
    { w:"nod", pos:"noun", d:"moving your head up and down for yes", ex:"She gave a quick nod and smiled." },
    { w:"wave", pos:"verb", d:"to move your hand to say hello or goodbye", ex:"The children wave at every passing train." },
    { w:"point", pos:"verb", d:"to show something with your finger", ex:"It is rude to point at people." },
    { w:"clap", pos:"verb", d:"to hit your hands together", ex:"The audience began to clap loudly." },
    { w:"stretch", pos:"verb", d:"to make your arms and legs long", ex:"Always stretch before you run." },
    { w:"yawn", pos:"noun", d:"opening your mouth wide when tired", ex:"His huge yawn made everyone else sleepy." },
    { w:"blink", pos:"verb", d:"to close and open your eyes quickly", ex:"Bright light makes you blink." },
    { w:"wink", pos:"noun", d:"closing one eye as a friendly signal", ex:"He gave me a friendly wink." },
    { w:"shrug", pos:"noun", d:"raising your shoulders to show you do not know", ex:"She answered with a silent shrug." },
    { w:"lean", pos:"verb", d:"to rest against something", ex:"Do not lean against the wet wall." },
  ]},
  { id:22, title:"The senses", emoji:"👁️", words:[
    { w:"sight", pos:"noun", d:"the ability to see", ex:"Eagles have amazing sight." },
    { w:"hearing", pos:"noun", d:"the ability to hear", ex:"A dog's hearing is much better than ours." },
    { w:"touch", pos:"noun", d:"the ability to feel with your skin", ex:"Babies learn about the world through touch." },
    { w:"stare", pos:"verb", d:"to look at something for a long time", ex:"It is impolite to stare at strangers." },
    { w:"glance", pos:"noun", d:"a very quick look", ex:"She took a quick glance at her watch." },
    { w:"whisper", pos:"verb", d:"to speak very quietly", ex:"Please whisper, the baby is sleeping." },
    { w:"scent", pos:"noun", d:"a pleasant smell", ex:"The scent of fresh bread filled the street." },
    { w:"deaf", pos:"adjective", d:"unable to hear", ex:"The deaf boy reads lips very well." },
    { w:"blind", pos:"adjective", d:"unable to see", ex:"The blind musician plays piano beautifully." },
    { w:"silent", pos:"adjective", d:"with no sound at all", ex:"The classroom went silent during the test." },
  ]},
  { id:24, title:"Injuries", emoji:"🩹", words:[
    { w:"injury", pos:"noun", d:"harm to your body", ex:"The player left the pitch with a knee injury." },
    { w:"wound", pos:"noun", d:"a deep cut on the body", ex:"The nurse cleaned the wound carefully." },
    { w:"bruise", pos:"noun", d:"a dark mark on skin after a hit", ex:"The fall left a purple bruise on his arm." },
    { w:"bleed", pos:"verb", d:"to lose blood", ex:"A small cut can bleed a lot." },
    { w:"burn", pos:"noun", d:"an injury from fire or heat", ex:"Cold water helps a small burn." },
    { w:"sprain", pos:"verb", d:"to hurt a joint by twisting it", ex:"You can sprain your ankle on these stairs." },
    { w:"swollen", pos:"adjective", d:"bigger than normal after an injury", ex:"His finger was swollen after the ball hit it." },
    { w:"plaster", pos:"noun", d:"a small sticky cover for a cut", ex:"She put a plaster on the blister." },
    { w:"crutches", pos:"noun", d:"sticks that help an injured person walk", ex:"He came to school on crutches." },
    { w:"heal", pos:"verb", d:"to become healthy again", ex:"Small cuts heal in a few days." },
  ]},
  { id:26, title:"At the hospital", emoji:"🏥", words:[
    { w:"ward", pos:"noun", d:"a room with beds in a hospital", ex:"The children's ward has colourful walls." },
    { w:"surgeon", pos:"noun", d:"a doctor who does operations", ex:"The surgeon washed her hands carefully." },
    { w:"operation", pos:"noun", d:"the act of cutting the body to fix it", ex:"The operation lasted three hours." },
    { w:"ambulance", pos:"noun", d:"the car that takes sick people to hospital", ex:"The ambulance arrived in five minutes." },
    { w:"stretcher", pos:"noun", d:"a bed for carrying an injured person", ex:"They carried the player off on a stretcher." },
    { w:"scan", pos:"noun", d:"a picture of the inside of the body", ex:"The scan showed the bone was fine." },
    { w:"therapy", pos:"noun", d:"treatment that helps you recover", ex:"Swimming therapy helped his back." },
    { w:"wheelchair", pos:"noun", d:"a chair with wheels for people who cannot walk", ex:"The hospital lent us a wheelchair." },
    { w:"treatment", pos:"noun", d:"medical care to make you better", ex:"The new treatment worked quickly." },
    { w:"cure", pos:"noun", d:"something that makes an illness go away", ex:"Laughter is the best cure, Grandma says." },
  ]}
);

sec("Home").units.push(
  { id:33, title:"Problems at home", emoji:"🔧", words:[
    { w:"leak", pos:"noun", d:"a hole where water gets out", ex:"There is a leak under the kitchen sink." },
    { w:"drip", pos:"verb", d:"to fall in small drops", ex:"The tap began to drip all night." },
    { w:"blocked", pos:"adjective", d:"so full that nothing can pass", ex:"The drain is blocked with leaves." },
    { w:"burst", pos:"verb", d:"to break open suddenly", ex:"The old pipe burst in the cold." },
    { w:"crack", pos:"noun", d:"a thin line where something is broken", ex:"A long crack appeared in the ceiling." },
    { w:"repair", pos:"verb", d:"to fix something broken", ex:"We must repair the fence before winter." },
    { w:"fix", pos:"verb", d:"to make something work again", ex:"Can you fix the broken lamp?" },
    { w:"fuse", pos:"noun", d:"a small part that stops too much electricity", ex:"The lights went off because a fuse blew." },
    { w:"ladder", pos:"noun", d:"steps you climb to reach high places", ex:"Hold the ladder while I check the roof." },
    { w:"handyman", pos:"noun", d:"a person who fixes things in homes", ex:"The handyman repaired three doors in an hour." },
  ]}
);

sec("Food & Drink").units.push(
  { id:34, title:"Meat and groceries", emoji:"🥩", words:[
    { w:"beef", pos:"noun", d:"meat from a cow", ex:"The soup needs half a kilo of beef." },
    { w:"mutton", pos:"noun", d:"meat from a sheep", ex:"Real plov is made with fresh mutton." },
    { w:"mince", pos:"noun", d:"meat cut into very small pieces", ex:"Add the mince to the hot pan." },
    { w:"sausage", pos:"noun", d:"meat in a long thin shape", ex:"He fried a sausage for breakfast." },
    { w:"flour", pos:"noun", d:"powder made from wheat for baking", ex:"Sift the flour before making the dough." },
    { w:"dough", pos:"noun", d:"the soft mix for making bread", ex:"Leave the dough to rise for an hour." },
    { w:"loaf", pos:"noun", d:"a whole piece of baked bread", ex:"She bought a warm loaf from the bakery." },
    { w:"grocer", pos:"noun", d:"a person who sells food in a small shop", ex:"The grocer always adds a free apple." },
    { w:"dairy", pos:"noun", d:"foods made from milk", ex:"Cheese and yoghurt are dairy products." },
    { w:"portion", pos:"noun", d:"the amount of food for one person", ex:"One portion of plov is never enough!" },
  ]}
);

sec("Free Time").units.push(
  { id:41, title:"Hobbies", emoji:"🎯", words:[
    { w:"jogging", pos:"noun", d:"slow running for exercise", ex:"He goes jogging around the stadium at dawn." },
    { w:"cycling", pos:"noun", d:"riding a bicycle", ex:"Cycling to school keeps me strong." },
    { w:"hiking", pos:"noun", d:"long walks in nature", ex:"We went hiking in the Chimgan mountains." },
    { w:"skating", pos:"noun", d:"moving on ice or wheels", ex:"The new park is perfect for skating." },
    { w:"drawing", pos:"noun", d:"making pictures with a pencil", ex:"Her drawing of the cat won a prize." },
    { w:"knitting", pos:"noun", d:"making clothes from wool with needles", ex:"Grandma's knitting basket is full of colours." },
    { w:"fishing", pos:"noun", d:"catching fish for fun", ex:"Dad took us fishing at the lake." },
    { w:"collection", pos:"noun", d:"a group of things you keep", ex:"His stamp collection fills three albums." },
    { w:"model", pos:"noun", d:"a small copy of something you build", ex:"He built a model of a pirate ship." },
    { w:"kite", pos:"noun", d:"a toy that flies on a string", ex:"The red kite danced in the wind." },
  ]},
  { id:42, title:"Activities", emoji:"🧗", words:[
    { w:"climbing", pos:"noun", d:"going up mountains or walls", ex:"Indoor climbing is safer for beginners." },
    { w:"surfing", pos:"noun", d:"riding waves on a board", ex:"You need big waves for surfing." },
    { w:"diving", pos:"noun", d:"swimming deep under water", ex:"Diving in the Red Sea is unforgettable." },
    { w:"bowling", pos:"noun", d:"a game of rolling balls at pins", ex:"We played bowling for his birthday." },
    { w:"archery", pos:"noun", d:"shooting arrows at a target", ex:"Archery needs a calm hand and sharp eyes." },
    { w:"karate", pos:"noun", d:"a Japanese fighting sport", ex:"She earned a black belt in karate." },
    { w:"yoga", pos:"noun", d:"slow exercises for body and mind", ex:"Morning yoga helps me stay calm." },
    { w:"skateboard", pos:"noun", d:"a board with wheels for riding", ex:"He learned a new trick on his skateboard." },
    { w:"picnic", pos:"noun", d:"a meal eaten outside for fun", ex:"We had a picnic under the apple trees." },
    { w:"sightseeing", pos:"noun", d:"visiting famous places", ex:"We spent a day sightseeing in Bukhara." },
  ]},
  { id:43, title:"Special days", emoji:"🎉", words:[
    { w:"celebration", pos:"noun", d:"a party for a special event", ex:"The celebration lasted until late evening." },
    { w:"festival", pos:"noun", d:"a big public celebration", ex:"The spring festival fills the streets with music." },
    { w:"fireworks", pos:"noun", d:"colourful explosions in the sky", ex:"The fireworks lit up the whole city." },
    { w:"parade", pos:"noun", d:"people marching through the streets", ex:"Dancers in bright costumes led the parade." },
    { w:"costume", pos:"noun", d:"special clothes for an event", ex:"She made a dragon costume for the show." },
    { w:"decoration", pos:"noun", d:"something that makes a place look festive", ex:"Every decoration on the tree was handmade." },
    { w:"present", pos:"noun", d:"a gift for a special day", ex:"The best present was a little kitten." },
    { w:"greeting", pos:"noun", d:"friendly words when you meet or write", ex:"She sent a warm greeting card to her teacher." },
    { w:"feast", pos:"noun", d:"a large special meal", ex:"The wedding feast had twelve different dishes." },
    { w:"national", pos:"adjective", d:"belonging to the whole country", ex:"Navruz is a national holiday in Uzbekistan." },
  ]},
  { id:45, title:"Books and art", emoji:"📚", words:[
    { w:"novel", pos:"noun", d:"a long story book", ex:"She reads one novel every week." },
    { w:"author", pos:"noun", d:"a person who writes books", ex:"The author signed my copy of the book." },
    { w:"poem", pos:"noun", d:"a piece of writing with rhythm", ex:"He wrote a poem about the autumn rain." },
    { w:"chapter", pos:"noun", d:"one part of a book", ex:"Just one more chapter before bed, please!" },
    { w:"gallery", pos:"noun", d:"a building that shows art", ex:"The gallery is free for students on Mondays." },
    { w:"exhibition", pos:"noun", d:"a public show of art or objects", ex:"The school held an exhibition of student paintings." },
    { w:"portrait", pos:"noun", d:"a picture of a person", ex:"The artist painted a portrait of my grandfather." },
    { w:"landscape", pos:"noun", d:"a picture of nature", ex:"The landscape shows mountains at sunrise." },
    { w:"sculpture", pos:"noun", d:"art made from stone, metal or wood", ex:"The ice sculpture melted by morning." },
    { w:"masterpiece", pos:"noun", d:"a perfect work of art", ex:"Critics call the film a masterpiece." },
  ]},
  { id:49, title:"Other sports", emoji:"🏅", words:[
    { w:"athletics", pos:"noun", d:"running, jumping and throwing sports", ex:"The athletics team trains every evening." },
    { w:"marathon", pos:"noun", d:"a running race of forty two kilometres", ex:"She finished her first marathon in five hours." },
    { w:"race", pos:"noun", d:"a competition of speed", ex:"The race starts at the old bridge." },
    { w:"sprint", pos:"noun", d:"a short, very fast run", ex:"He won the hundred metre sprint." },
    { w:"gymnastics", pos:"noun", d:"a sport of strength and balance", ex:"Gymnastics needs years of practice." },
    { w:"boxing", pos:"noun", d:"a fighting sport with gloves", ex:"Boxing matches have three rounds here." },
    { w:"wrestling", pos:"noun", d:"a sport of holding and throwing an opponent", ex:"Kurash is traditional Uzbek wrestling." },
    { w:"weightlifting", pos:"noun", d:"a sport of lifting heavy weights", ex:"Weightlifting builds strong shoulders." },
    { w:"medal", pos:"noun", d:"the metal prize for winners", ex:"She wore her gold medal to school." },
    { w:"stadium", pos:"noun", d:"a big building for sports and fans", ex:"The whole stadium sang together." },
  ]},
  { id:50, title:"Results and scores", emoji:"🏆", words:[
    { w:"victory", pos:"noun", d:"a win in a game or competition", ex:"The team celebrated a famous victory." },
    { w:"defeat", pos:"noun", d:"a loss in a game", ex:"They learned more from defeat than from winning." },
    { w:"winner", pos:"noun", d:"the person or team that wins", ex:"The winner gets a cup and flowers." },
    { w:"beat", pos:"verb", d:"to win against someone", ex:"Our school can beat any team in chess." },
    { w:"championship", pos:"noun", d:"a competition to find the best", ex:"The championship final is on Sunday." },
    { w:"record", pos:"noun", d:"the best result ever", ex:"She broke the national record in swimming." },
    { w:"qualify", pos:"verb", d:"to earn a place in the next stage", ex:"Two teams qualify from each group." },
    { w:"final", pos:"noun", d:"the last match that decides the winner", ex:"The final finished with penalties." },
    { w:"cheer", pos:"verb", d:"to shout support for a team", ex:"The fans cheer louder in the second half." },
    { w:"deserve", pos:"verb", d:"to have earned something", ex:"You deserve first place after such practice." },
  ]}
);

sec("Clothes & Shopping").units.push(
  { id:57, title:"Money basics", emoji:"💵", words:[
    { w:"cash", pos:"noun", d:"money in coins and notes", ex:"The market only accepts cash." },
    { w:"purse", pos:"noun", d:"a small bag for money", ex:"Her purse is full of old bus tickets." },
    { w:"change", pos:"noun", d:"the money given back after paying", ex:"The cashier counted my change twice." },
    { w:"pay", pos:"verb", d:"to give money for something", ex:"You can pay at the counter." },
    { w:"cost", pos:"verb", d:"to need a certain amount of money", ex:"The trip will cost less in spring." },
    { w:"cheap", pos:"adjective", d:"not costing much money", ex:"Tomatoes are cheap in August." },
    { w:"expensive", pos:"adjective", d:"costing a lot of money", ex:"That phone is too expensive for me." },
    { w:"price", pos:"noun", d:"how much money something costs", ex:"The price of bread went up again." },
    { w:"salary", pos:"noun", d:"the monthly money you get for your job", ex:"She saves half her salary every month." },
    { w:"pocket money", pos:"noun", d:"money parents give to children", ex:"He spends his pocket money on comics." },
  ]},
  { id:59, title:"At the bank", emoji:"🏦", words:[
    { w:"account", pos:"noun", d:"your personal money place at a bank", ex:"Dad opened an account for my savings." },
    { w:"deposit", pos:"noun", d:"money you put into a bank", ex:"She made a deposit after her first salary." },
    { w:"withdraw", pos:"verb", d:"to take money out of a bank", ex:"You can withdraw cash at the machine." },
    { w:"exchange", pos:"verb", d:"to change one currency into another", ex:"Where can I exchange dollars for som?" },
    { w:"loan", pos:"noun", d:"money you borrow and pay back", ex:"They took a loan to open a bakery." },
    { w:"interest", pos:"noun", d:"extra money paid on savings or loans", ex:"The bank pays five percent interest." },
    { w:"transfer", pos:"noun", d:"sending money from one account to another", ex:"The transfer arrived in two minutes." },
    { w:"savings", pos:"noun", d:"money you keep for the future", ex:"Her savings grew slowly but surely." },
    { w:"currency", pos:"noun", d:"the money of a country", ex:"The som is the currency of Uzbekistan." },
    { w:"secure", pos:"adjective", d:"safe from thieves", ex:"Keep your password secure and secret." },
  ]}
);
const rich = sec("Clothes & Shopping").units.find(u=>u.id===58);
if (rich) rich.title = "Rich and poor";

sec("School & Work").units.push(
  { id:68, title:"Further education", emoji:"🎓", words:[
    { w:"university", pos:"noun", d:"the place for higher study", ex:"She studies medicine at university." },
    { w:"degree", pos:"noun", d:"the qualification from a university", ex:"He has a degree in computer science." },
    { w:"scholarship", pos:"noun", d:"money given to a good student to study", ex:"The scholarship covers all her fees." },
    { w:"lecture", pos:"noun", d:"a long talk that teaches something", ex:"The history lecture lasted two hours." },
    { w:"professor", pos:"noun", d:"a senior university teacher", ex:"The professor knows seven languages." },
    { w:"campus", pos:"noun", d:"the land and buildings of a university", ex:"The campus has its own football pitch." },
    { w:"graduate", pos:"verb", d:"to finish university successfully", ex:"She will graduate next summer." },
    { w:"diploma", pos:"noun", d:"an official paper proving your study", ex:"His diploma hangs on the office wall." },
    { w:"course", pos:"noun", d:"a series of lessons on one subject", ex:"I joined an online course in design." },
    { w:"research", pos:"noun", d:"careful study to find new facts", ex:"Her research is about desert plants." },
  ]},
  { id:71, title:"Looking for a job", emoji:"💼", words:[
    { w:"application", pos:"noun", d:"the form you send to ask for a job", ex:"Send your application before Friday." },
    { w:"apply", pos:"verb", d:"to officially ask for a job or place", ex:"You can apply for three universities." },
    { w:"interview", pos:"noun", d:"a meeting where you answer questions for a job", ex:"Wear something smart for the interview." },
    { w:"employer", pos:"noun", d:"the person or company that gives jobs", ex:"The employer called her the next day." },
    { w:"employee", pos:"noun", d:"a person who works for a company", ex:"Every employee gets free lunch here." },
    { w:"experience", pos:"noun", d:"the skills you get from doing work", ex:"The job needs two years of experience." },
    { w:"qualification", pos:"noun", d:"an exam result or skill you officially have", ex:"A teaching qualification takes years of work." },
    { w:"vacancy", pos:"noun", d:"a job that is free to take", ex:"The cafe has a vacancy for a waiter." },
    { w:"hire", pos:"verb", d:"to give someone a job", ex:"They decided to hire the young designer." },
    { w:"reference", pos:"noun", d:"a letter saying you are a good worker", ex:"Her old boss wrote a glowing reference." },
  ]},
  { id:72, title:"Working life", emoji:"🏢", words:[
    { w:"shift", pos:"noun", d:"a fixed period of work time", ex:"The night shift starts at ten." },
    { w:"overtime", pos:"noun", d:"extra hours of work", ex:"He did overtime to finish the project." },
    { w:"wages", pos:"noun", d:"money paid for work, often weekly", ex:"The workers receive their wages on Friday." },
    { w:"promotion", pos:"noun", d:"a move to a better job position", ex:"She celebrated her promotion with the team." },
    { w:"boss", pos:"noun", d:"the person in charge at work", ex:"My boss lets us leave early on hot days." },
    { w:"staff", pos:"noun", d:"all the workers of a company", ex:"The staff planted trees behind the office." },
    { w:"resign", pos:"verb", d:"to officially leave your job", ex:"He decided to resign and open his own shop." },
    { w:"day off", pos:"noun", d:"a day when you do not work", ex:"Sunday is her only day off." },
    { w:"pension", pos:"noun", d:"money paid after you retire", ex:"Grandpa spends his pension on his garden." },
    { w:"schedule", pos:"noun", d:"a plan of times for doing things", ex:"Check the schedule before the meeting." },
  ]},
  { id:73, title:"In the office", emoji:"🖇️", words:[
    { w:"folder", pos:"noun", d:"a cover for keeping papers", ex:"Put the reports in the blue folder." },
    { w:"stapler", pos:"noun", d:"a tool that joins papers together", ex:"The stapler is out of staples again." },
    { w:"printer", pos:"noun", d:"a machine that puts text on paper", ex:"The printer is jammed once more." },
    { w:"photocopier", pos:"noun", d:"a machine that copies documents", ex:"Make ten copies on the photocopier." },
    { w:"envelope", pos:"noun", d:"a paper cover for a letter", ex:"Write the address on the envelope clearly." },
    { w:"stationery", pos:"noun", d:"pens, paper and office things", ex:"The new stationery cupboard is full." },
    { w:"meeting", pos:"noun", d:"when people gather to discuss work", ex:"The morning meeting took only ten minutes." },
    { w:"report", pos:"noun", d:"a written document about something", ex:"Finish the sales report by Monday." },
    { w:"drawer", pos:"noun", d:"a sliding box in a desk", ex:"The keys are in the top drawer." },
    { w:"notice", pos:"noun", d:"a written announcement for everyone", ex:"A notice on the door said the office was closed." },
  ]},
  { id:74, title:"Business", emoji:"📈", words:[
    { w:"company", pos:"noun", d:"an organisation that sells things or services", ex:"Her company makes shoes for children." },
    { w:"profit", pos:"noun", d:"the money left after paying costs", ex:"The bakery made a good profit in spring." },
    { w:"loss", pos:"noun", d:"when a business loses money", ex:"One bad month brought a big loss." },
    { w:"client", pos:"noun", d:"a person who pays for a service", ex:"The designer met her new client at nine." },
    { w:"product", pos:"noun", d:"a thing made to be sold", ex:"Their newest product sold out in a day." },
    { w:"brand", pos:"noun", d:"the name and image of a company", ex:"Everyone recognises this sports brand." },
    { w:"factory", pos:"noun", d:"a building where products are made", ex:"The factory employs half the town." },
    { w:"export", pos:"verb", d:"to sell goods to other countries", ex:"They export dried fruit to many countries." },
    { w:"import", pos:"verb", d:"to buy goods from other countries", ex:"We import coffee from Brazil." },
    { w:"deal", pos:"noun", d:"a business agreement", ex:"The two companies signed a big deal." },
  ]}
);
})();
