// CTN Vocab — Part 4: Travel & Transport, Media & Tech, Society & History, World & Nature+, Ideas & Numbers
(function(){
const sec = n => VOCAB.sections.find(s=>s.name===n);

const travel = { name:"Travel & Transport", emoji:"✈️", units:[
  { id:61, title:"Holidays", emoji:"🏝️", words:[
    { w:"holiday", pos:"noun", d:"a time of rest away from work or school", ex:"Our summer holiday starts next week." },
    { w:"destination", pos:"noun", d:"the place you travel to", ex:"Istanbul is a popular destination this year." },
    { w:"brochure", pos:"noun", d:"a small book advertising holidays", ex:"The brochure showed white beaches and palms." },
    { w:"pack", pos:"verb", d:"to put things into bags for a trip", ex:"Pack a warm jacket for the mountains." },
    { w:"suitcase", pos:"noun", d:"a large bag for travelling", ex:"Her suitcase was five kilos too heavy." },
    { w:"journey", pos:"noun", d:"the act of travelling somewhere", ex:"The train journey takes six hours." },
    { w:"tour", pos:"noun", d:"a visit around a place", ex:"We took a tour of the old fortress." },
    { w:"guide", pos:"noun", d:"a person who shows tourists around", ex:"The guide told amazing stories about the castle." },
    { w:"souvenir", pos:"noun", d:"a thing you buy to remember a place", ex:"This magnet is a souvenir from Khiva." },
    { w:"postcard", pos:"noun", d:"a card with a picture you send from trips", ex:"Send me a postcard from Paris!" },
  ]},
  { id:62, title:"Beach holidays", emoji:"🏖️", words:[
    { w:"sunbathe", pos:"verb", d:"to lie in the sun", ex:"Tourists sunbathe by the pool all day." },
    { w:"sunscreen", pos:"noun", d:"cream that protects skin from the sun", ex:"Put on sunscreen before swimming." },
    { w:"sandcastle", pos:"noun", d:"a castle built from sand", ex:"The waves washed away our sandcastle." },
    { w:"tide", pos:"noun", d:"the daily rise and fall of the sea", ex:"Check the tide before you swim far." },
    { w:"shore", pos:"noun", d:"the land at the edge of the sea", ex:"Shells covered the quiet shore." },
    { w:"seaside", pos:"noun", d:"the area near the sea", ex:"They rent a small house at the seaside." },
    { w:"snorkel", pos:"noun", d:"a tube for breathing while swimming face down", ex:"With a snorkel you can watch the fish." },
    { w:"sunburn", pos:"noun", d:"red painful skin from too much sun", ex:"His shoulders got a bad sunburn." },
    { w:"deckchair", pos:"noun", d:"a folding chair for the beach", ex:"Grandpa slept in his deckchair till lunch." },
    { w:"lifeguard", pos:"noun", d:"a person who keeps swimmers safe", ex:"The lifeguard watched the sea all afternoon." },
  ]},
  { id:63, title:"Forms of transport", emoji:"🚌", words:[
    { w:"vehicle", pos:"noun", d:"any machine that carries people or things", ex:"This road is closed to every vehicle." },
    { w:"lorry", pos:"noun", d:"a big truck for carrying goods", ex:"A lorry delivered the new furniture." },
    { w:"van", pos:"noun", d:"a medium vehicle for carrying things", ex:"The bakery van smells of fresh bread." },
    { w:"tram", pos:"noun", d:"an electric vehicle on rails in streets", ex:"The old tram still runs through the centre." },
    { w:"ferry", pos:"noun", d:"a boat that carries people and cars", ex:"The ferry crosses the river every hour." },
    { w:"helicopter", pos:"noun", d:"an aircraft with spinning blades", ex:"A helicopter landed near the hospital." },
    { w:"scooter", pos:"noun", d:"a small two wheeled vehicle", ex:"He rides an electric scooter to work." },
    { w:"underground", pos:"noun", d:"the railway under a city", ex:"The Tashkent underground has beautiful stations." },
    { w:"motorway", pos:"noun", d:"a wide fast road between cities", ex:"The new motorway cut the trip in half." },
    { w:"cargo", pos:"noun", d:"goods carried by ship, plane or truck", ex:"The plane carries cargo at night." },
  ]},
  { id:64, title:"Cars", emoji:"🚗", words:[
    { w:"engine", pos:"noun", d:"the part that makes a car move", ex:"The engine makes a strange noise." },
    { w:"brake", pos:"noun", d:"the part that stops the car", ex:"Test the brake before driving downhill." },
    { w:"steering wheel", pos:"noun", d:"the wheel the driver turns", ex:"Keep both hands on the steering wheel." },
    { w:"seatbelt", pos:"noun", d:"the belt that keeps you safe in a car", ex:"Fasten your seatbelt before we start." },
    { w:"windscreen", pos:"noun", d:"the front window of a car", ex:"Rain covered the windscreen in seconds." },
    { w:"boot", pos:"noun", d:"the storage space at the back of a car", ex:"The watermelons filled the whole boot." },
    { w:"bonnet", pos:"noun", d:"the cover of the car engine", ex:"Smoke came from under the bonnet." },
    { w:"horn", pos:"noun", d:"the part that makes a warning sound", ex:"He pressed the horn at the sleepy cow." },
    { w:"tyre", pos:"noun", d:"the rubber ring around a wheel", ex:"The front tyre is flat again." },
    { w:"headlight", pos:"noun", d:"the strong light at the front of a car", ex:"One headlight stopped working at night." },
  ]},
  { id:65, title:"Driving", emoji:"🚦", words:[
    { w:"accelerate", pos:"verb", d:"to go faster", ex:"The car began to accelerate on the motorway." },
    { w:"overtake", pos:"verb", d:"to pass a slower car", ex:"Never overtake on a bend." },
    { w:"reverse", pos:"verb", d:"to drive backwards", ex:"She can reverse into the smallest space." },
    { w:"crash", pos:"noun", d:"an accident between vehicles", ex:"Nobody was hurt in the small crash." },
    { w:"skid", pos:"verb", d:"to slide without control", ex:"Cars skid easily on icy roads." },
    { w:"licence", pos:"noun", d:"the official permission to drive", ex:"He got his driving licence at eighteen." },
    { w:"lane", pos:"noun", d:"one line of traffic on a road", ex:"Stay in the right lane for the exit." },
    { w:"speed limit", pos:"noun", d:"the fastest legal speed", ex:"The speed limit here is sixty." },
    { w:"indicator", pos:"noun", d:"the blinking light showing your turn", ex:"Use your indicator before turning." },
    { w:"pedestrian", pos:"noun", d:"a person walking on the street", ex:"Stop when a pedestrian is crossing." },
  ]},
  { id:66, title:"Public transport", emoji:"🚇", words:[
    { w:"passenger", pos:"noun", d:"a person travelling in a vehicle", ex:"The last passenger ran for the bus." },
    { w:"fare", pos:"noun", d:"the money you pay for a trip", ex:"The bus fare went up to two thousand." },
    { w:"platform", pos:"noun", d:"where you wait for a train", ex:"The train leaves from platform four." },
    { w:"route", pos:"noun", d:"the way a bus or train travels", ex:"This route passes the city park." },
    { w:"delay", pos:"noun", d:"when transport is late", ex:"A two hour delay ruined our plans." },
    { w:"rush hour", pos:"noun", d:"the busy travel time of day", ex:"Avoid the metro during rush hour." },
    { w:"ticket", pos:"noun", d:"the paper that lets you travel", ex:"Keep your ticket until the end." },
    { w:"inspector", pos:"noun", d:"a person who checks tickets", ex:"The inspector smiled and checked our tickets." },
    { w:"commute", pos:"noun", d:"the daily trip between home and work", ex:"His commute takes forty minutes each way." },
    { w:"board", pos:"verb", d:"to get on a bus, train or plane", ex:"Passengers may board the train now." },
  ]},
]};

const media = { name:"Media & Tech", emoji:"📺", units:[
  { id:51, title:"Television", emoji:"🎥", words:[
    { w:"channel", pos:"noun", d:"a TV station", ex:"Switch to the sports channel, please." },
    { w:"programme", pos:"noun", d:"a show on TV", ex:"Her favourite programme starts at eight." },
    { w:"series", pos:"noun", d:"a story told in many episodes", ex:"We watched the whole series in one weekend." },
    { w:"episode", pos:"noun", d:"one part of a series", ex:"The last episode made everyone cry." },
    { w:"presenter", pos:"noun", d:"the person who leads a TV show", ex:"The presenter welcomed the young singer." },
    { w:"documentary", pos:"noun", d:"a film about real life", ex:"The documentary about oceans won awards." },
    { w:"viewer", pos:"noun", d:"a person watching TV", ex:"Every viewer voted for their favourite." },
    { w:"broadcast", pos:"verb", d:"to send out a TV or radio programme", ex:"They broadcast the match live from Tashkent." },
    { w:"quiz", pos:"noun", d:"a game show with questions", ex:"Our team won the school quiz." },
    { w:"live", pos:"adjective", d:"shown as it happens", ex:"The concert was shown live on TV." },
  ]},
  { id:52, title:"Newspapers", emoji:"📰", words:[
    { w:"headline", pos:"noun", d:"the big title of a news story", ex:"The headline was about the missing painting." },
    { w:"article", pos:"noun", d:"a piece of writing in a newspaper", ex:"She wrote an article about school lunches." },
    { w:"reporter", pos:"noun", d:"a person who collects and tells news", ex:"The reporter asked the mayor hard questions." },
    { w:"editor", pos:"noun", d:"the person who decides what news to print", ex:"The editor cut the story in half." },
    { w:"column", pos:"noun", d:"a regular article by the same writer", ex:"His weekly column makes everyone laugh." },
    { w:"gossip", pos:"noun", d:"talk about other people's lives", ex:"Do not believe playground gossip." },
    { w:"magazine", pos:"noun", d:"a thin book with pictures and articles", ex:"The science magazine comes once a month." },
    { w:"publish", pos:"verb", d:"to print for people to read", ex:"They will publish her story in May." },
    { w:"daily", pos:"adjective", d:"happening or printed every day", ex:"He reads two daily newspapers." },
    { w:"source", pos:"noun", d:"where information comes from", ex:"A good reporter never reveals a source." },
  ]},
  { id:53, title:"Advertising", emoji:"📢", words:[
    { w:"advertisement", pos:"noun", d:"a message that tries to sell something", ex:"The advertisement showed a flying car." },
    { w:"slogan", pos:"noun", d:"a short memorable phrase", ex:"Their slogan is just three words long." },
    { w:"logo", pos:"noun", d:"the symbol of a company", ex:"The logo appears on every bottle." },
    { w:"poster", pos:"noun", d:"a large printed picture or notice", ex:"A huge poster covered the old wall." },
    { w:"billboard", pos:"noun", d:"a giant board for street adverts", ex:"The billboard lights up at night." },
    { w:"commercial", pos:"noun", d:"an advert on TV or radio", ex:"The funny commercial made Dad laugh." },
    { w:"campaign", pos:"noun", d:"a planned series of adverts", ex:"The summer campaign doubled their sales." },
    { w:"persuade", pos:"verb", d:"to make someone decide to do something", ex:"Adverts persuade us to buy things we do not need." },
    { w:"target", pos:"noun", d:"the group an advert is made for", ex:"Teenagers are the target of this advert." },
    { w:"catchy", pos:"adjective", d:"easy to remember, like a tune", ex:"The song is so catchy I sing it all day." },
  ]},
  { id:55, title:"Computers", emoji:"💻", words:[
    { w:"keyboard", pos:"noun", d:"the buttons you type on", ex:"My keyboard has a broken space bar." },
    { w:"mouse", pos:"noun", d:"the small device that moves the cursor", ex:"Click the right button of the mouse." },
    { w:"laptop", pos:"noun", d:"a computer you can carry", ex:"Her laptop battery lasts all day." },
    { w:"download", pos:"verb", d:"to copy something from the internet", ex:"It takes a minute to download the game." },
    { w:"upload", pos:"verb", d:"to send a file to the internet", ex:"Upload your homework before midnight." },
    { w:"password", pos:"noun", d:"the secret word that protects your account", ex:"Never share your password with friends." },
    { w:"software", pos:"noun", d:"the programs a computer runs", ex:"The new software makes editing easy." },
    { w:"website", pos:"noun", d:"a place you visit on the internet", ex:"The school website shows all the marks." },
    { w:"click", pos:"verb", d:"to press a mouse button", ex:"Click the green button to start." },
    { w:"install", pos:"verb", d:"to put a program onto a computer", ex:"Ask before you install new games." },
  ]},
  { id:56, title:"Machines", emoji:"🔌", words:[
    { w:"gadget", pos:"noun", d:"a small clever device", ex:"This gadget peels apples in seconds." },
    { w:"device", pos:"noun", d:"a machine made for one purpose", ex:"Turn off every device before bed." },
    { w:"battery", pos:"noun", d:"the part that stores power", ex:"The battery died during the film." },
    { w:"plug", pos:"noun", d:"the part you put into a socket", ex:"The plug does not fit this socket." },
    { w:"switch", pos:"noun", d:"the button that turns things on and off", ex:"The light switch is behind the door." },
    { w:"remote control", pos:"noun", d:"the device for controlling a TV from far away", ex:"The remote control is lost in the sofa again." },
    { w:"washing machine", pos:"noun", d:"the machine that washes clothes", ex:"The washing machine sings when it finishes." },
    { w:"freezer", pos:"noun", d:"the very cold part of a fridge", ex:"There is ice cream hiding in the freezer." },
    { w:"heater", pos:"noun", d:"a machine that warms a room", ex:"Turn on the heater, it is freezing." },
    { w:"drill", pos:"noun", d:"a tool that makes holes", ex:"The drill woke up the whole building." },
  ]},
  { id:84, title:"Science", emoji:"🔬", words:[
    { w:"experiment", pos:"noun", d:"a test to learn something new", ex:"Our experiment with magnets worked!" },
    { w:"laboratory", pos:"noun", d:"a room for scientific work", ex:"Wear safety glasses in the laboratory." },
    { w:"scientist", pos:"noun", d:"a person who studies how the world works", ex:"The scientist explained her discovery simply." },
    { w:"chemistry", pos:"noun", d:"the science of substances", ex:"Chemistry lessons always smell interesting." },
    { w:"physics", pos:"noun", d:"the science of energy and matter", ex:"Physics explains why planes fly." },
    { w:"biology", pos:"noun", d:"the science of living things", ex:"In biology we studied the human heart." },
    { w:"theory", pos:"noun", d:"an idea that explains facts", ex:"Her theory explains the strange results." },
    { w:"discover", pos:"verb", d:"to find something for the first time", ex:"Scientists discover new species every year." },
    { w:"invent", pos:"verb", d:"to create something that never existed", ex:"She wants to invent a translation hat." },
    { w:"gravity", pos:"noun", d:"the force that pulls things down", ex:"Gravity makes the apple fall." },
  ]},
  { id:85, title:"Materials", emoji:"🧱", words:[
    { w:"leather", pos:"noun", d:"material made from animal skin", ex:"His leather boots lasted ten years." },
    { w:"wool", pos:"noun", d:"material from sheep hair", ex:"This wool scarf was made by Grandma." },
    { w:"cotton", pos:"noun", d:"soft material from a plant", ex:"Uzbek cotton is famous worldwide." },
    { w:"silk", pos:"noun", d:"smooth shiny material from silkworms", ex:"Margilan is the home of Uzbek silk." },
    { w:"plastic", pos:"noun", d:"light artificial material", ex:"Use less plastic to help the planet." },
    { w:"steel", pos:"noun", d:"very strong metal", ex:"The bridge is made of steel and stone." },
    { w:"rubber", pos:"noun", d:"material that bends and bounces", ex:"Car tyres are made of rubber." },
    { w:"concrete", pos:"noun", d:"the building material of cement and stones", ex:"The new school is built from concrete." },
    { w:"cardboard", pos:"noun", d:"thick stiff paper", ex:"We made a robot costume from cardboard." },
    { w:"fabric", pos:"noun", d:"any cloth material", ex:"She chose a bright fabric for the dress." },
  ]},
]};

const society = { name:"Society & History", emoji:"🏛️", units:[
  { id:75, title:"Crime and punishment", emoji:"👮", words:[
    { w:"crime", pos:"noun", d:"an action that breaks the law", ex:"Stealing is a serious crime." },
    { w:"criminal", pos:"noun", d:"a person who breaks the law", ex:"The criminal was caught the same day." },
    { w:"arrest", pos:"noun", d:"when police take someone away", ex:"The arrest happened outside the bank." },
    { w:"trial", pos:"noun", d:"the court process that decides guilt", ex:"The trial lasted three weeks." },
    { w:"judge", pos:"noun", d:"the person who leads a court", ex:"The judge listened to both sides." },
    { w:"jury", pos:"noun", d:"the group that decides if someone is guilty", ex:"The jury talked for five hours." },
    { w:"prison", pos:"noun", d:"the building where criminals are kept", ex:"He spent two years in prison." },
    { w:"guilty", pos:"adjective", d:"having done the crime", ex:"The court found him guilty." },
    { w:"innocent", pos:"adjective", d:"not guilty of the crime", ex:"New evidence proved she was innocent." },
    { w:"punishment", pos:"noun", d:"what someone gets for doing wrong", ex:"The punishment should fit the crime." },
  ]},
  { id:76, title:"Solving crime", emoji:"🕵️", words:[
    { w:"witness", pos:"noun", d:"a person who saw what happened", ex:"The witness described the blue car." },
    { w:"victim", pos:"noun", d:"the person hurt by a crime", ex:"The victim got all her money back." },
    { w:"investigate", pos:"verb", d:"to try to find out the truth", ex:"Detectives investigate every small detail." },
    { w:"detective", pos:"noun", d:"a police officer who solves crimes", ex:"The detective noticed the muddy shoes." },
    { w:"evidence", pos:"noun", d:"facts that prove something", ex:"The fingerprints were strong evidence." },
    { w:"suspect", pos:"noun", d:"a person police think did the crime", ex:"The suspect had a perfect alibi." },
    { w:"murder", pos:"noun", d:"the crime of killing a person", ex:"The film is about an unsolved murder." },
    { w:"kidnap", pos:"verb", d:"to take a person away illegally", ex:"In the story, pirates kidnap the captain." },
    { w:"fraud", pos:"noun", d:"tricking people to get their money", ex:"Online fraud is growing every year." },
    { w:"gang", pos:"noun", d:"a group of criminals", ex:"Police stopped the gang at the border." },
  ]},
  { id:77, title:"Theft and burglary", emoji:"🔒", words:[
    { w:"thief", pos:"noun", d:"a person who steals", ex:"The thief took only the old painting." },
    { w:"steal", pos:"verb", d:"to take something that is not yours", ex:"It is wrong to steal, even a pencil." },
    { w:"burglar", pos:"noun", d:"a thief who enters buildings", ex:"The burglar came through the kitchen window." },
    { w:"rob", pos:"verb", d:"to steal from a person or place", ex:"Two men tried to rob the bank." },
    { w:"pickpocket", pos:"noun", d:"a thief who steals from pockets", ex:"A pickpocket works fast in crowded buses." },
    { w:"shoplifting", pos:"noun", d:"stealing from shops", ex:"Cameras help stop shoplifting." },
    { w:"break in", pos:"phrasal verb", d:"to enter a building illegally", ex:"Someone tried to break in last night." },
    { w:"alarm", pos:"noun", d:"a loud warning sound system", ex:"The alarm scared the burglar away." },
    { w:"lock", pos:"noun", d:"the metal thing that keeps doors closed", ex:"Check the lock before you leave." },
    { w:"valuables", pos:"noun", d:"things worth a lot of money", ex:"Keep your valuables in the hotel safe." },
  ]},
  { id:78, title:"War and peace", emoji:"🕊️", words:[
    { w:"war", pos:"noun", d:"fighting between countries", ex:"The museum tells the story of the war." },
    { w:"peace", pos:"noun", d:"a time with no war", ex:"Everyone hopes for lasting peace." },
    { w:"army", pos:"noun", d:"the soldiers of a country", ex:"His grandfather served in the army." },
    { w:"soldier", pos:"noun", d:"a person who fights for a country", ex:"The young soldier wrote home every week." },
    { w:"weapon", pos:"noun", d:"a thing used for fighting", ex:"The sword was the knight's main weapon." },
    { w:"battle", pos:"noun", d:"one fight in a war", ex:"The battle lasted until sunset." },
    { w:"enemy", pos:"noun", d:"the side you fight against", ex:"The old enemy became a friend." },
    { w:"treaty", pos:"noun", d:"an official agreement between countries", ex:"The peace treaty was signed in spring." },
    { w:"refugee", pos:"noun", d:"a person who must leave home because of war", ex:"The refugee family opened a small bakery." },
    { w:"ceasefire", pos:"noun", d:"an agreement to stop fighting", ex:"The ceasefire began at midnight." },
  ]},
  { id:79, title:"Politics", emoji:"🏛️", words:[
    { w:"government", pos:"noun", d:"the group that runs a country", ex:"The government opened three new schools." },
    { w:"president", pos:"noun", d:"the elected leader of a country", ex:"The president visited our region today." },
    { w:"election", pos:"noun", d:"when people vote to choose leaders", ex:"The election takes place in December." },
    { w:"vote", pos:"verb", d:"to choose officially", ex:"People vote at eighteen here." },
    { w:"parliament", pos:"noun", d:"the group that makes laws", ex:"Parliament debated the new law all night." },
    { w:"minister", pos:"noun", d:"a leader of one government area", ex:"The education minister visited our school." },
    { w:"policy", pos:"noun", d:"an official plan of action", ex:"The new policy supports young farmers." },
    { w:"debate", pos:"noun", d:"a formal argument about ideas", ex:"The class held a debate about homework." },
    { w:"law", pos:"noun", d:"an official rule of a country", ex:"The new law protects wild animals." },
    { w:"democracy", pos:"noun", d:"a system where people choose their leaders", ex:"Democracy depends on free elections." },
  ]},
  { id:80, title:"Religion", emoji:"🕌", words:[
    { w:"religion", pos:"noun", d:"a system of belief in God or gods", ex:"Students learn about every world religion." },
    { w:"mosque", pos:"noun", d:"the building where Muslims pray", ex:"The old mosque has a turquoise dome." },
    { w:"church", pos:"noun", d:"the building where Christians pray", ex:"The church bells ring on Sunday morning." },
    { w:"temple", pos:"noun", d:"a holy building in some religions", ex:"The golden temple shone in the sun." },
    { w:"pray", pos:"verb", d:"to speak to God", ex:"Many people pray before meals." },
    { w:"faith", pos:"noun", d:"strong belief in God or an idea", ex:"Her faith gave her strength in hard times." },
    { w:"holy", pos:"adjective", d:"connected with God; sacred", ex:"Pilgrims visit the holy city every year." },
    { w:"belief", pos:"noun", d:"something you accept as true", ex:"Respect for elders is a core belief here." },
    { w:"worship", pos:"noun", d:"showing love and respect to God", ex:"The temple is a place of worship." },
    { w:"charity", pos:"noun", d:"giving help to people in need", ex:"The charity built wells in dry villages." },
  ]},
  { id:81, title:"Social issues", emoji:"🤲", words:[
    { w:"homeless", pos:"adjective", d:"without a place to live", ex:"Volunteers cook for homeless people in winter." },
    { w:"unemployment", pos:"noun", d:"the state of having no job", ex:"Unemployment fell after the new factory opened." },
    { w:"inequality", pos:"noun", d:"when people are not treated equally", ex:"The report shows inequality between regions." },
    { w:"volunteer", pos:"noun", d:"a person who helps for free", ex:"Every volunteer received a thank you letter." },
    { w:"donate", pos:"verb", d:"to give money or things to help", ex:"They donate books to village schools." },
    { w:"community", pos:"noun", d:"the people living in one area", ex:"The whole community cleaned the river banks." },
    { w:"disability", pos:"noun", d:"a condition that limits what your body can do", ex:"The centre supports children with every disability." },
    { w:"aid", pos:"noun", d:"help given to people in need", ex:"Trucks carried aid to the flooded town." },
    { w:"justice", pos:"noun", d:"fair treatment for everyone", ex:"People marched peacefully for justice." },
    { w:"awareness", pos:"noun", d:"knowing about a problem", ex:"The posters raise awareness about clean water." },
  ]},
  { id:86, title:"History", emoji:"🏺", words:[
    { w:"ancient", pos:"adjective", d:"from thousands of years ago", ex:"Samarkand is an ancient city on the Silk Road." },
    { w:"empire", pos:"noun", d:"many countries ruled by one leader", ex:"The empire stretched from sea to sea." },
    { w:"ruler", pos:"noun", d:"a person who governs a country", ex:"Amir Timur was a powerful ruler." },
    { w:"castle", pos:"noun", d:"a strong building from the past", ex:"The castle stood on the highest hill." },
    { w:"knight", pos:"noun", d:"a fighting horseman of the past", ex:"The knight polished his silver armour." },
    { w:"revolution", pos:"noun", d:"a sudden complete change of power", ex:"The revolution changed the whole country." },
    { w:"independence", pos:"noun", d:"freedom from control by others", ex:"Uzbekistan celebrates independence in September." },
    { w:"monument", pos:"noun", d:"a structure built to remember something", ex:"A monument marks the poet's birthplace." },
    { w:"archaeology", pos:"noun", d:"the study of ancient things in the ground", ex:"Archaeology brings lost cities back to light." },
    { w:"ancestor", pos:"noun", d:"a family member from long ago", ex:"Every ancestor in the album has a story." },
  ]},
]};

const before = VOCAB.sections.findIndex(s=>s.name==="World & Nature");
VOCAB.sections.splice(before, 0, travel, media, society);

sec("World & Nature").units.push(
  { id:83, title:"The natural world", emoji:"🌿", words:[
    { w:"desert", pos:"noun", d:"dry land with little rain", ex:"The Kyzylkum desert glows gold at sunset." },
    { w:"valley", pos:"noun", d:"low land between mountains", ex:"The valley is green even in August." },
    { w:"waterfall", pos:"noun", d:"water falling from a high place", ex:"We could hear the waterfall from far away." },
    { w:"cave", pos:"noun", d:"a natural hole in rock or ground", ex:"Bats sleep in the cool dark cave." },
    { w:"cliff", pos:"noun", d:"a high steep rock face", ex:"Seabirds nest on the white cliff." },
    { w:"stream", pos:"noun", d:"a small narrow river", ex:"Cold water ran fast in the mountain stream." },
    { w:"meadow", pos:"noun", d:"a field of grass and flowers", ex:"Bees hummed across the summer meadow." },
    { w:"jungle", pos:"noun", d:"a thick hot forest", ex:"Parrots screamed high in the jungle." },
    { w:"horizon", pos:"noun", d:"the line where sky meets land", ex:"A ship appeared on the horizon." },
    { w:"wilderness", pos:"noun", d:"wild land untouched by people", ex:"They hiked deep into the wilderness." },
  ]},
  { id:89, title:"Disasters", emoji:"🌋", words:[
    { w:"earthquake", pos:"noun", d:"sudden shaking of the ground", ex:"The earthquake woke the whole city." },
    { w:"flood", pos:"noun", d:"too much water covering the land", ex:"The flood reached the school steps." },
    { w:"drought", pos:"noun", d:"a long time with no rain", ex:"The drought dried out the cotton fields." },
    { w:"volcano", pos:"noun", d:"a mountain that can erupt fire", ex:"The volcano slept for a thousand years." },
    { w:"avalanche", pos:"noun", d:"a huge slide of snow down a mountain", ex:"The avalanche closed the mountain road." },
    { w:"hurricane", pos:"noun", d:"a giant storm with very strong winds", ex:"The hurricane turned boats upside down." },
    { w:"tornado", pos:"noun", d:"a spinning column of wind", ex:"The tornado lifted the roof off a barn." },
    { w:"wildfire", pos:"noun", d:"a fire spreading through nature", ex:"Rain finally stopped the wildfire." },
    { w:"rescue", pos:"noun", d:"saving someone from danger", ex:"The rescue team worked through the night." },
    { w:"survivor", pos:"noun", d:"a person who lives through a disaster", ex:"Every survivor was given warm food." },
  ]},
  { id:92, title:"Talking about animals", emoji:"🐾", words:[
    { w:"tame", pos:"adjective", d:"not wild, friendly to people", ex:"The deer in the park are quite tame." },
    { w:"stray", pos:"adjective", d:"a pet animal without a home", ex:"They adopted a stray kitten from the street." },
    { w:"paw", pos:"noun", d:"the foot of an animal", ex:"The dog gave me his muddy paw." },
    { w:"claw", pos:"noun", d:"the sharp nail of an animal", ex:"The cat sharpened every claw on the chair." },
    { w:"feather", pos:"noun", d:"one piece of a bird's coat", ex:"A peacock feather is full of colours." },
    { w:"fur", pos:"noun", d:"the soft hair of an animal", ex:"The rabbit's fur is softer than silk." },
    { w:"tail", pos:"noun", d:"the part at the back of an animal", ex:"The happy dog wagged its tail." },
    { w:"cage", pos:"noun", d:"a box of bars for keeping animals", ex:"The parrot's cage door was open." },
    { w:"bark", pos:"noun", d:"the sound a dog makes", ex:"His deep bark scared the postman." },
    { w:"purr", pos:"verb", d:"to make the happy sound of a cat", ex:"The kitten began to purr on my lap." },
  ]}
);

VOCAB.sections.push({ name:"Ideas & Numbers", emoji:"🧠", units:[
  { id:96, title:"Similarity and difference", emoji:"⚖️", words:[
    { w:"similar", pos:"adjective", d:"almost the same", ex:"The twins have similar voices." },
    { w:"identical", pos:"adjective", d:"exactly the same", ex:"The two paintings are almost identical." },
    { w:"alike", pos:"adjective", d:"like each other", ex:"Father and son think alike." },
    { w:"differ", pos:"verb", d:"to be different", ex:"The two plans differ in price." },
    { w:"compare", pos:"verb", d:"to look at differences and similarities", ex:"Compare the two phones before buying." },
    { w:"contrast", pos:"noun", d:"a clear difference", ex:"The contrast between day and night temperatures is huge." },
    { w:"opposite", pos:"adjective", d:"completely different", ex:"Hot is the opposite of cold." },
    { w:"unique", pos:"adjective", d:"the only one of its kind", ex:"Every snowflake is unique." },
    { w:"resemble", pos:"verb", d:"to look like", ex:"You really resemble your grandfather." },
    { w:"common", pos:"adjective", d:"shared by many; usual", ex:"The two languages have many common words." },
  ]},
  { id:97, title:"Thoughts and ideas", emoji:"💭", words:[
    { w:"imagine", pos:"verb", d:"to make a picture in your mind", ex:"Imagine a city under the sea." },
    { w:"suppose", pos:"verb", d:"to think something is probably true", ex:"I suppose the shop is closed by now." },
    { w:"doubt", pos:"verb", d:"to feel something may not be true", ex:"I doubt it will rain today." },
    { w:"consider", pos:"verb", d:"to think about carefully", ex:"Consider both answers before choosing." },
    { w:"realise", pos:"verb", d:"to suddenly understand", ex:"Did you realise the test is tomorrow?" },
    { w:"wonder", pos:"verb", d:"to ask yourself about something", ex:"I wonder what dolphins dream about." },
    { w:"assume", pos:"verb", d:"to believe without proof", ex:"Never assume the answer is easy." },
    { w:"concentrate", pos:"verb", d:"to give all your attention", ex:"It is hard to concentrate in a noisy room." },
    { w:"memorise", pos:"verb", d:"to learn so you remember exactly", ex:"She can memorise twenty words a day." },
    { w:"brilliant", pos:"adjective", d:"extremely clever or excellent", ex:"What a brilliant idea for the project!" },
  ]},
  { id:98, title:"Size and shape", emoji:"📏", words:[
    { w:"enormous", pos:"adjective", d:"extremely big", ex:"An enormous watermelon won the contest." },
    { w:"tiny", pos:"adjective", d:"extremely small", ex:"A tiny bird landed on my finger." },
    { w:"gigantic", pos:"adjective", d:"huge like a giant", ex:"A gigantic balloon floated over the stadium." },
    { w:"narrow", pos:"adjective", d:"not wide", ex:"The narrow street fits only one car." },
    { w:"wide", pos:"adjective", d:"big from side to side", ex:"The river is too wide to swim across." },
    { w:"circular", pos:"adjective", d:"shaped like a circle", ex:"The stadium has a circular roof." },
    { w:"triangular", pos:"adjective", d:"shaped like a triangle", ex:"Samsa has a triangular shape." },
    { w:"curved", pos:"adjective", d:"bent like part of a circle", ex:"The bridge has a gently curved design." },
    { w:"hollow", pos:"adjective", d:"empty inside", ex:"The old tree trunk was completely hollow." },
    { w:"thick", pos:"adjective", d:"big from one side to the other; not thin", ex:"The castle walls are three metres thick." },
  ]},
  { id:99, title:"Distance and speed", emoji:"🚀", words:[
    { w:"distance", pos:"noun", d:"the space between two places", ex:"The distance to the lake is ten kilometres." },
    { w:"distant", pos:"adjective", d:"far away", ex:"We heard distant thunder in the mountains." },
    { w:"nearby", pos:"adjective", d:"close, not far", ex:"There is a nearby park with a pool." },
    { w:"rapid", pos:"adjective", d:"very fast", ex:"The city saw rapid growth in ten years." },
    { w:"gradual", pos:"adjective", d:"happening slowly step by step", ex:"There was a gradual change in the weather." },
    { w:"pace", pos:"noun", d:"the speed of movement", ex:"Walk at a comfortable pace." },
    { w:"kilometre", pos:"noun", d:"a unit of distance, one thousand metres", ex:"The bridge is exactly one kilometre long." },
    { w:"halfway", pos:"adverb", d:"in the middle of the distance", ex:"We rested halfway up the hill." },
    { w:"swift", pos:"adjective", d:"quick and smooth", ex:"The swift river carried the boat away." },
    { w:"steady", pos:"adjective", d:"regular and not changing", ex:"Keep a steady speed on the motorway." },
  ]},
  { id:100, title:"Quantities", emoji:"🧮", words:[
    { w:"amount", pos:"noun", d:"how much there is of something", ex:"A small amount of salt is enough." },
    { w:"plenty", pos:"noun", d:"more than enough", ex:"We have plenty of time before the train." },
    { w:"several", pos:"adjective", d:"more than two but not many", ex:"Several students missed the bus." },
    { w:"enough", pos:"adjective", d:"as much as needed", ex:"Is there enough bread for everyone?" },
    { w:"hardly", pos:"adverb", d:"almost not at all", ex:"I could hardly hear the quiet music." },
    { w:"entire", pos:"adjective", d:"whole, complete", ex:"The entire class passed the exam." },
    { w:"majority", pos:"noun", d:"more than half of a group", ex:"The majority chose pizza for the party." },
    { w:"minority", pos:"noun", d:"less than half of a group", ex:"Only a small minority disagreed." },
    { w:"handful", pos:"noun", d:"a small number", ex:"Just a handful of tickets are left." },
    { w:"heap", pos:"noun", d:"a large messy pile", ex:"A heap of clothes covered the chair." },
  ]},
]});
})();
